select  ID , NAMESURNAME, GENDER, BIRTHDATE, CITY, TOWN, TELNR, TCNUMBER from CUSTOMERS


truncate table CUSTOMERS

DELETE from CUSTOMERS

insert into CUSTOMERS ( NAMESURNAME, GENDER, BIRTHDATE, CITY, TOWN, TELNR, TCNUMBER ) values ('Ömer Çolakoğlu','E','1990-01-16','Istanbul','Kadikoy','05321234567','12345678901')