SELECT * from CUSTOMERS WHERE NAMESURNAME<>'FARUK TULUM'

insert into CUSTOMERS ( NAMESURNAME,GENDER ,BIRTHDATE,CITY,TOWN) VALUES ('MEHMET KARAGÖL','E','1985-01-01','MANİSA','AKHİSAR')
insert into CUSTOMERS ( NAMESURNAME,GENDER ,BIRTHDATE,CITY,TOWN) VALUES ('MAHMUT KAÇAR','E','1974-10-24','BURDUR','BUCAK')

UPDATE CUSTOMERS SET AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())
DELETE FROM CUSTOMERS WHERE ID=3
--ID DEĞERİ IDENTİTY OLDUĞU İÇİN DEĞİŞTİREMEYİZ 
--UPDATE CUSTOMERS SET ID=3 WHERE ID=1004

SELECT * FROM CUSTOMERS WHERE ID > 1000
SELECT * from Customers where NAMESURNAME > 'D'

select * from Customers WHERE NAMESURNAME LIKE 'ÖMER%' --ÖMER İLE BAŞLAYANLAR
select * from Customers WHERE NAMESURNAME LIKE 'FARUK%' -- FARUK İLE BAŞLAYANLAR
select * from Customers WHERE NAMESURNAME LIKE '%FARUK%' --İÇİNDE FARUK GEÇENLER
SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE '% FARUK % ' -- İKİNCİ İSMİ FARUK OLANLAR 
select * from Customers WHERE NAMESURNAME LIKE '%TULUM'  -- TULUM İLE BİTENLER
SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE 'C%'  -- C HARFİ İLE BAŞLAYAN KAYITLAR
SELECT * FROM CUSTOMERS WHERE NAMESURNAME NOT LIKE '%FARUK%'

SELECT * FROM CUSTOMERS WHERE ID BETWEEN 1000 AND 2000
SELECT * FROM CUSTOMERS WHERE BIRTHDATE BETWEEN '1960-01-01' AND '2000-01-01'

SELECT * FROM CUSTOMERS WHERE ID IN (1,4,1007)
SELECT * FROM CUSTOMERS WHERE CITY IN ('ÇANAKKALE','AYDIN')

UPDATE  CUSTOMERS SET GSMOPERATOR=NULL 
UPDATE CUSTOMERS SET GSMOPERATOR='TURKCELL' WHERE ID=1
UPDATE CUSTOMERS SET GSMOPERATOR='TURKCELL' WHERE CITY='ÇANAKKALE'

SELECT * FROM CUSTOMERS WHERE GSMOPERATOR IS NOT NULL
DELETE FROM CUSTOMERS WHERE CITY = 'BURDUR '

