SELECT *
FROM CUSTOMERS
WHERE ID = 1
SELECT *
FROM CUSTOMERS
WHERE GENDER = 'E'
SELECT *
FROM CUSTOMERS
WHERE GENDER <> 'K'
SELECT *
FROM CUSTOMERS
WHERE NOT GENDER = 'K'
SELECT *
FROM CUSTOMERS
WHERE BIRTHDATE = '1990-08-17'
SELECT *
FROM CUSTOMERS
WHERE NAMESURNAME = 'MELİS TÜRKMEN'

SELECT *
FROM CUSTOMERS
WHERE ID > 100
SELECT *
FROM CUSTOMERS
WHERE ID < 100
SELECT *
FROM CUSTOMERS
WHERE ID <= 100
SELECT *
FROM CUSTOMERS
WHERE BIRTHDATE < '1990-01-01'
SELECT *
FROM CUSTOMERS
WHERE BIRTHDATE <= '1990-12-31'
SELECT *
FROM CUSTOMERS
WHERE ID BETWEEN 100 AND 200
SELECT *
FROM CUSTOMERS
WHERE NAMESURNAME < 'D'
SELECT *
FROM CUSTOMERS
WHERE NAMESURNAME BETWEEN 'K' AND 'N'

SELECT *
FROM CUSTOMERS
WHERE NAMESURNAME LIKE 'ALİ%'
SELECT *
FROM CUSTOMERS
WHERE NAMESURNAME LIKE 'ALİ %'
SELECT *
FROM CUSTOMERS
WHERE NAMESURNAME LIKE '% ALİ %'
SELECT *
FROM CUSTOMERS
WHERE NAMESURNAME LIKE '%CAN%'
SELECT *
FROM CUSTOMERS
WHERE NAMESURNAME LIKE '%CAN'
SELECT *
FROM CUSTOMERS
WHERE NAMESURNAME LIKE '% CAN'

update CUSTOMERS set GENDER='ERKEK' WHERE GENDER='E'
UPDATE CUSTOMERS SET GENDER='KADIN' WHERE GENDER='K'
UPDATE CUSTOMERS SET AGE= NULL
UPDATE CUSTOMERS SET AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())
SELECT *
FROM CUSTOMERS
WHERE AGE IN (21,23,33,43,53,63)
UPDATE CUSTOMERS SET AGEGROUP = 'GENÇ' WHERE AGE BETWEEN 20 AND 40
UPDATE CUSTOMERS SET AGEGROUP = 'ORTA YAŞLI' WHERE AGE BETWEEN 40 AND 60
UPDATE CUSTOMERS SET AGEGROUP = 'YAŞLI' WHERE AGE > 60

DELETE FROM CUSTOMERS WHERE ID = 1
DELETE FROM CUSTOMERS WHERE NAMESURNAME = 'UĞUR GÖNENÇ'
DELETE FROM CUSTOMERS WHERE CITY ='ISTANBUL'
DELETE FROM CUSTOMERS WHERE AGE < 30 
DELETE FROM CUSTOMERS WHERE AGEGROUP  = 'ORTA YASLI'

SELECT * FROM CUSTOMERS WHERE CITY='ÇANAKKALE' AND GENDER='ERKEK' AND TOWN='BİGA' 
SELECT * FROM CUSTOMERS WHERE CITY='ÇANAKKALE' OR GENDER = 'ERKEK'
SELECT * FROM CUSTOMERS WHERE CITY='İZMİR' AND (TOWN='BİGA' OR TOWN='LAPSEKİ')


UPDATE CUSTOMERS SET  AGE = DATEDIFF(YEAR,BIRTHDATE,GETDATE())
SELECT * FROM CUSTOMERS WHERE CITY='ÇANAKKALE' AND GENDER='ERKEK'
SELECT * FROM CUSTOMERS WHERE NAMESURNAME LIKE 'A%' AND AGE BETWEEN 40 AND 50 
SELECT * FROM CUSTOMERS WHERE CITY='ISTANBUL' AND (AGEGROUP='GENÇ' OR AGEGROUP='YAŞLI')
SELECT * FROM CUSTOMERS WHERE CITY='ÇANAKKALE' AND (AGE BETWEEN 20 AND 30 OR AGE BETWEEN 40 AND 50)

UPDATE CUSTOMERS SET CATEGORY='GENÇ ERKEK' WHERE GENDER='ERKEK' AND AGE BETWEEN 20 AND 40  
UPDATE CUSTOMERS SET CATEGORY='ORTA YAŞLI ERKEK' WHERE GENDER= 'ERKEK' AND AGE BETWEEN 41 AND 60
UPDATE CUSTOMERS SET CATEGORY='YAŞLI ERKEK ' WHERE GENDER='ERKEK' AND AGE >60
UPDATE CUSTOMERS SET CATEGORY='GENÇ KADIN' WHERE GENDER='KADIN' AND AGE BETWEEN 20 AND 40 
UPDATE CUSTOMERS SET CATEGORY='ORTA YAŞLI KADIN' WHERE GENDER='KADIN' AND AGE BETWEEN 41 AND 60
UPDATE CUSTOMERS SET CATEGORY='YAŞLI KADIN' WHERE GENDER='KADIN' AND AGE >60
SELECT * FROM CUSTOMERS WHERE CITY='ÇANAKKALE' AND (CATEGORY='YAŞLI ERKEK' OR CATEGORY='GENÇ ERKEK')
SELECT * FROM CUSTOMERS WHERE CITY='ÇANAKKALE' AND (TOWN='BİGA' OR TOWN='LAPSEKİ' OR TOWN ='BORNOVA') AND (CATEGORY='YAŞLI ERKEK' OR CATEGORY='GENÇ ERKEK')
SELECT * FROM CUSTOMERS WHERE CITY='ÇANAKKALE' AND TOWN IN ('BİGA','LAPSEKİ') AND CATEGORY IN ('YAŞLI ERKEK','GENÇ ERKEK')
