-- DECLARE @CITY AS VARCHAR(50)
-- DECLARE CRS CURSOR FOR SELECT ID , CITY FROM CITIES 
-- OPEN CRS 
-- FETCH NEXT FROM CRS INTO @ID,@CITY
-- WHILE @@FETCHSTATUS=0
-- BEGIN
-- SELECT @ID,@CITY
-- FETCH NEXT FROM CRS INTO @ID,@CITY
-- END
-- CLOSE CRS
-- DEALLOCATE CRS

-- ALISTIRMA 1 
-- CREATE PROC GETITEMINCOME
-- @ITEMID AS INT
-- AS
-- BEGIN
-- SELECT I.ID,I.ITEMCODE, I.ITEMNAME,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,I.UNITPRICE,
-- SUM(OD.AMOUNT) TOTALAMOUNT,SUM(OD.LINETOTAL) TOTALSALE,I.UNITPRICE*SUM(OD.AMOUNT) COST,
-- SUM(OD.LINETOTAL)/(I.UNITPRICE*SUM(OD.AMOUNT))-1 INCOMEPERCENT
--  FROM ORDERDETAILS OD  JOIN ITEMS I ON OD.ITEMID = I.ID WHERE I.ID =@ITEMID GROUP BY I.ID,I.ITEMCODE, I.ITEMNAME,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,I.UNITPRICE

-- END

EXEC GETITEMINCOME  5

-- CREATE TABLE #T ( ID INT ,ITEMCODE VARCHAR(20),ITEMNAME VARCHAR(100),CATEGORY1 VARCHAR(50),CATEGORY2 VARCHAR(50),CATEGORY3 VARCHAR(50),
-- UNITPRICE FLOAT,TOTALAMOUNT INT,TOTALSALE   FLOAT, COST FLOAT,INCOMEPERCENT FLOAT
-- )
INSERT INTO #T EXEC GETITEMINCOME 5
SELECT * FROM #T

TRUNCATE TABLE #T
DECLARE @ID AS INT
DECLARE CRS CURSOR FOR SELECT ID FROM ITEMS -- WHERE CATEGORY1='GIDA'
OPEN CRS 
FETCH NEXT FROM CRS INTO @ID
WHILE @@FETCH_STATUS=0
BEGIN 
INSERT INTO #T EXEC GETITEMINCOME @ID
FETCH NEXT FROM CRS INTO @ID
END
CLOSE CRS 
DEALLOCATE CRS

SELECT * FROM #T

SELECT AVG(INCOMEPERCENT) FROM #T
SELECT CATEGORY1,AVG(INCOMEPERCENT) FROM #T GROUP BY CATEGORY1

DROP TABLE #T