-- DEGISKEN TANIMLAMA
DECLARE @ISIM AS VARCHAR(100)
SET @ISIM = 'ÖMER ÇOLAKOĞLU'
SELECT @ISIM

PRINT @ISIM

-- NUMERIC DEGISKENLER
DECLARE @SAYI1 AS INT
DECLARE @SAYI2 AS INT
DECLARE @SONUC AS INT

SET @SAYI1 = 10
SET @SAYI2 = 20
SET @SONUC = @SAYI1 * @SAYI2

SELECT @SAYI1 SAYI1 ,@SAYI2 SAYI2,@SONUC SONUC

-- DATETIME DEGISKENLER

DECLARE @TARIH AS DATETIME
SET @TARIH = '2022-12-24 14:36:52' 
SELECT @TARIH

SELECT DATEDIFF(YEAR,'1950-01-01',@TARIH)
SELECT DATEADD(MONTH,3,@TARIH)
SELECT DATEPART(MONTH,@TARIH)  SELECT DATENAME(MONTH,@TARIH)


-- SQL SORGUSUNDAN GELEN DEGERI  DEGISKENE ATAMA  
DECLARE @ROWCOUNT AS INT 
DECLARE @TOTALPRICE AS FLOAT
DECLARE @TOTALAMOUNT AS INT
DECLARE @CUSTOMERCOUNT AS INT

SELECT @ROWCOUNT = COUNT(*) FROM SALES WHERE CITY= 'İSTANBUL'
SET @TOTALPRICE = (SELECT  SUM(TOTALPRICE) FROM SALES WHERE CITY= 'İSTANBUL')

SELECT @ROWCOUNT=COUNT(*) , @TOTALPRICE=SUM(TOTALPRICE) ,@TOTALAMOUNT= SUM(AMOUNT) ,@CUSTOMERCOUNT=COUNT(DISTINCT CUSTOMERCODE) FROM SALES WHERE CITY='İSTANBUL'

SELECT @ROWCOUNT , @TOTALPRICE, @TOTALAMOUNT,@CUSTOMERCOUNT

-- SQL SORGUSUNA DEGISKEN GONDERME 

DECLARE @CITY AS VARCHAR(100) = 'BURSA'
DECLARE @BEGDATE AS DATE = '20220401'
DECLARE @ENDDATE AS DATE = '20220501'

SET @BEGDATE = '20220401'
SET @ENDDATE = '20220501'
SET @CITY='İZMİR'

SELECT * FROM SALES WHERE CITY=@CITY AND DATE_ BETWEEN @BEGDATE AND @ENDDATE

-- ALISTIRMA 1

DECLARE @NAME  VARCHAR(50) = 'OMER FARUK'
DECLARE @SURNAME VARCHAR(50) = 'TULUM'

-- SET @NAME = 'OMER FARUK'
-- SET @SURNAME = 'TULUM'

DECLARE @NAMESURNAME  VARCHAR(100)
-- SET @NAMESURNAME =  @NAME + ' '+ @SURNAME
SET @NAMESURNAME = CONCAT(@NAME,' ',@SURNAME)

SELECT @NAMESURNAME 
PRINT @NAMESURNAME

-- ALISTIRMA 2

DECLARE @DT DATETIME 
DECLARE @D AS DATE
DECLARE @T AS TIME
DECLARE @DSTR VARCHAR(100)
DECLARE @TSTR VARCHAR(100)


SET @DT = '2022-06-24 12:56:21'
SET @D = @DT
SET @T = @DT

SET @DSTR = CONVERT(VARCHAR,@D,104)

SET @TSTR = CONVERT(VARCHAR,@T,108)
SELECT @DT DT,@D D,@T T,@DSTR DSTR,@TSTR TSTR

-- ALISTIRMA 3


DECLARE @MSG AS VARCHAR(1000) = 'SAYIN <NAMESURNAME> <AGE>. YASINIZI KUTLAR MUTLU YILLAR DILERIZ'
SET @MSG = 'SAYIN '+ @NAMESURNAME + '55. YASINIZI KUTLAR MUTLU YILLAR DILERIZ'

DECLARE  @MONTH AS INT
DECLARE @DAY  AS INT
DECLARE @BIRTHDATE AS DATE
DECLARE @AGE AS INT
SET @MONTH=DATEPART(MONTH,GETDATE())
SET @DAY = DATEPART(DAY,GETDATE())

SELECT @MONTH,@DAY

SELECT TOP 1 @NAME = NAME_,@SURNAME = SURNAME,@BIRTHDATE= BIRTHDATE FROM LAB03
WHERE DATEPART (MONTH,BIRTHDATE)=@MONTH AND
DATEPART(DAY,BIRTHDATE) = @DAY
ORDER BY NEWID()

SET @NAMESURNAME = @NAME + ' '+ @SURNAME
SET @AGE = DATEDIFF(YEAR,@BIRTHDATE,GETDATE())

SET @MSG = REPLACE(@MSG,'<NAMESURNAME>',@NAMESURNAME)
SET @MSG = REPLACE(@MSG,'<AGE>',CONVERT(VARCHAR,@AGE))

SELECT @NAME NAME_,@SURNAME SURNAME,@BIRTHDATE BIRTHDATE,@NAMESURNAME NAMESURNAME,@AGE AGE,@MSG MSG

-- ALISTIRMA 4 

SELECT * FROM NAMES
SELECT * FROM SURNAMES
SELECT * FROM CITIES

DECLARE @NAME AS VARCHAR(100)
DECLARE @GENDER AS VARCHAR(1)
DECLARE @SURNAME AS VARCHAR(100)
DECLARE @CITY AS VARCHAR(100)
DECLARE @BIRTHDATE AS DATE
DECLARE @NAMESURNAME AS VARCHAR(100)
DECLARE @RAND AS INT

SET @RAND = 1 + RAND()*609
SELECT TOP 1 @NAME = NAME_ ,@GENDER= GENDER FROM NAMES WHERE ID=@RAND


SET @RAND = 1 + RAND()*797
SELECT TOP 1 @SURNAME= SURNAME FROM SURNAMES WHERE ID=@RAND


SET @RAND =  RAND()*50*365
SET @BIRTHDATE=DATEADD(DAY,@RAND,'1950-01-01')

SET @NAMESURNAME = @NAME + ' ' + @SURNAME

SELECT @NAME NAME_,@GENDER GENDER,@SURNAME SURNAME,@NAMESURNAME NAMESURNAME,@BIRTHDATE BIRTHDATE

-- ALISTIRMA 5 

DECLARE @USERID AS INT
DECLARE @ITEMID AS INT
DECLARE @DATE AS DATETIME  
DECLARE @AMOUNT AS INT
DECLARE @UNITPRICE AS FLOAT
DECLARE @LINETOTAL AS FLOAT
DECLARE @RAND AS INT

SELECT TOP 1 @USERID = ID FROM USERS ORDER BY NEWID()
SELECT TOP 1 @ITEMID = ID, @UNITPRICE = UNITPRICE FROM ITEMS ORDER BY NEWID()

SET @RAND= RAND()*365
SET @DATE = DATEADD(DAY,@RAND,'20220101')

SET @RAND = 28800 + RAND()*43200
SET @DATE  =DATEADD(SECOND,@RAND,@DATE)

SET @AMOUNT = 1 + RAND() * 19

SET @LINETOTAL = @AMOUNT * @UNITPRICE

SELECT @USERID USERID,@ITEMID ITEMID , @DATE DATE_, @AMOUNT AMOUNT,@UNITPRICE UNITPRICE,@LINETOTAL LINETOTAL

INSERT INTO SALES2 (USERID,ITEMID,DATE_,AMOUNT,UNITPRICE,LINETOTAL) VALUES (@USERID,@ITEMID,@DATE,@AMOUNT,@UNITPRICE,@LINETOTAL)

SELECT U.USERNAME,I.ITEMNAME,S.*
FROM SALES S 
JOIN USERS U ON U.ID=S.CUSTOMERID 
JOIN ITEMS I ON I.ID=S.ITEMID

-- ALISTIRMA 6 
DECLARE @BEGDATE AS DATE = '2019-06-01'
DECLARE @ENDDATE AS DATE = '2019-07-01'
DECLARE @CITY AS VARCHAR(200)='ADANA,İSTANBUL,ANKARA'

-- SELECT * FROM SALES
SELECT CITY , SUM(TOTALPRICE) FROM SALES WHERE DATE_ BETWEEN @BEGDATE AND @ENDDATE AND CITY IN  (SELECT * FROM string_split(@CITY,',')) 
GROUP  BY CITY 