-- GO DONGUSU
INSERT INTO DATES
    (DATE_)
VALUES(GETDATE())
GO
10
SELECT *
FROM DATES

-- WHILE DONGUSU

DECLARE @I AS INT = 0

WHILE @I < 10 
    BEGIN
    INSERT INTO DATES
        (DATE_)
    VALUES(GETDATE())
    SET @I=@I+1
END

-- ALISTIRMA 1 

DECLARE I AS INT
WHILE I<1000
    BEGIN
    DECLARE @DEVICEID AS INT = 1
    DECLARE @LASTVALUE AS FLOAT
    DECLARE @LASTDATE AS DATETIME
    DECLARE @CURRENTVALUE AS FLOAT
    DECLARE @DATE AS DATETIME
    DECLARE @RAND AS FLOAT
    DECLARE @RAND2 AS INT

    SET @DEVICEID = 1+RAND(99)

    SET @RAND = 2*(-0.5+RAND())
    SET @CURRENTVALUE = @LASTVALUE + ROUND(@RAND,2)

    SET @RAND2 = 15 + RAND()*15
    SET @DATE = DATEADD(SECOND,@RAND2,@LASTDATE)

    SELECT @LASTVALUE = LASTVALUE , @LASTDATE = LASTDATE
    FROM THERMOMETERS
    WHERE ID = @DEVICEID

    SELECT @DEVICEID DEVICEID, @LASTVALUE LASTVALUE, @LASTDATE LASTDATE, @CURRENTVALUE CURRENTVALUE, @DATE DATE_

    INSERT INTO THERMOVALUES
        (DEVICEID,VALUE_,DATE_)
    VALUES
        ( @DEVICEID, @CURRENTVALUE, @DATE)
    UPDATE THERMOMETERS SET LASTDATE = @DATE,LASTVALUE=@CURRENTVALUE WHERE ID=@DEVICEID

    SET @I = @I + 1

END

SELECT * FROM THERMOVALUES
SELECT * FROM THERMOMETERS WHERE ID = 1
SELECT * FROM THERMOVALUES WHERE DEVICEID= 1
ORDER BY DATE_

-- ALISTIRMA 2 
SELECT * FROM CUSTOMERS

DECLARE @I AS INT = 1
WHILE @I <100 
    BEGIN

DECLARE @NAME  AS VARCHAR(100)
DECLARE @SURNAME  AS VARCHAR(100)
DECLARE @NAMESURNAME  AS VARCHAR(100)
DECLARE @GENDER AS VARCHAR(1)
DECLARE @BIRTHDATE AS DATE
DECLARE @CITY AS VARCHAR(100)
DECLARE @RAND AS INT

SELECT TOP 1 @NAME = NAME_ ,@GENDER = GENDER FROM NAMES ORDER BY NEWID()
SELECT TOP 1 @SURNAME = SURNAME FROM SURNAMES ORDER BY NEWID()
SELECT TOP 1 @CITY = CITYNAME FROM CITIES ORDER BY NEWID()


SET @RAND = RAND()*365*50
SET @BIRTHDATE = DATEADD(DAY,@RAND,'1950-01-01')
SET @NAMESURNAME = @NAME+' '+@SURNAME

INSERT INTO CUSTOMERS2 (NAME_,SURNAME,GENDER,NAMESURNAME,CITY,BIRTHDATE) VALUES
(@NAME,@SURNAME,@GENDER,@NAMESURNAME,@CITY,@BIRTHDATE)
SET @I=@I+1
END
SELECT @NAME NAME_ , @SURNAME SURNAME , @GENDER GENDER,@NAMESURNAME NAMESURNAME,@CITY CITY,@BIRTHDATE BIRTHDATE

TRUNCATE TABLE CUSTOMERS2
SELECT * FROM CUSTOMERS2

-- ALISTIRMA 3

DECLARE @USERID AS INT
DECLARE @ADDRESSID AS INT
DECLARE @DATE_ AS DATETIME
DECLARE @STATUS AS INT =1
DECLARE @TOTALPRICE AS FLOAT

DECLARE @ORDERID AS INT
DECLARE @ITEMID AS INT
DECLARE @AMOUNT AS INT
DECLARE @UNITPRICE AS FLOAT
DECLARE @LINETOTAL AS FLOAT
DECLARE @RAND AS INT

SELECT TOP 1 @USERID = ID FROM USERS ORDER  BY NEWID()
SELECT TOP 1 @ADDRESSID = ID FROM ADDRESS WHERE USERID = 100 ORDER BY NEWID()
SET @RAND = RAND()*365
SET @DATE_ = DATEADD(DAY,@RAND,'2019-01-01')
SET @RAND = RAND()*86400
SET @DATE_ = DATEADD(SECOND,@RAND,@DATE_)

INSERT INTO ORDERS (USERID,ADDRESSID,DATE_,STATUS_,TOTALPRICE) VALUES
(@USERID,@ADDRESSID,@DATE_,@STATUS,@TOTALPRICE)

SELECT @ORDERID=@@IDENTITY 
SELECT TOP 1 @ITEMID = ID,@UNITPRICE = UNITPRICE FROM ITEMS ORDER BY NEWID()
SET @RAND=1+RAND()*9
SET @AMOUNT=@RAND
SET @LINETOTAL = @AMOUNT * @UNITPRICE

INSERT INTO ORDERDETAILS(ORDERID,ITEMID,AMOUNT,UNITPRICE,LINETOTAL) 
VALUES(@ORDERID,@ITEMID,@AMOUNT,@UNITPRICE,@LINETOTAL)

UPDATE ORDERS SET TOTALPRICE = (SELECT SUM(LINETOTAL) FROM ORDERDETAILS WHERE ORDERID=ORDERS.ID) 
WHERE ID=@ORDERID

GO 1000
SELECT * FROM ORDERS ORDER BY 1 DESC
SELECT @USERID USERID , @ADDRESSID ADDRESSID,@DATE_ DATE_,@TOTALPRICE TOTALPRICE