-- ABS VE SIGN FONKSIYONLARI
SELECT ABS(26.9),ABS(-25),SIGN(-5),SIGN(5),SIGN(0)

-- ROUND FLOOR CEILING FONKSIYONLARI
SELECT 214.4678 ORIGINAL,ROUND(214.4678,2) ROUND_,FLOOR(214.4678)FLOOR_,CEILING(214.4678) CEILING_

-- RAND FONKSIYONU (0 İLE 1 ARASINDA FLOAT DEGERLER URETIR )
SELECT RAND()

-- ALISTIRMA 1 

SELECT 
ROUND(SUM(TOTALPRICE),0 ) YUVARLAMADAN_  ,
SUM(ROUND(TOTALPRICE,0)) ROUND_ ,
FLOOR(ROUND(TOTALPRICE,0)) FLOOR_ ,
SUM(CEILING(TOTALPRICE,0)) CEILING_ ,

-- ALISTIRMA 2

SELECT '1. TAKIM' ACIKLAMA_,
TEAM_LONG_NAME TAKIM_UZUN_ADI,
TEAM_SHORT_NAME TAKIM_KISA_ADI,
FROM LAB02
WHERE ID=FLOOR(1+RAND()*298)


SELECT '2. TAKIM' ACIKLAMA_,
TEAM_LONG_NAME TAKIM_UZUN_ADI,
TEAM_SHORT_NAME TAKIM_KISA_ADI,
FROM LAB02
WHERE ID=FLOOR(1+RAND()*298)


-- ALISTIRMA 3
SELECT CUSTOMERID ,
SUM(ABS(AMOUNT)) TOTALVOLUME ,
SUM(AMOUNT) TOTALBALANCE FROM LAB03
GROUP BY CUSTOMERID
ORDER BY 1 
