SELECT ROW_NUMBER() OVER (PARTITION BY BRAND ORDER BY UNITPRICE DESC) ROWNUMBER,UNITPRICE,* FROM ITEMS
ORDER BY BRAND,ID

SELECT ROW_NUMBER() OVER (ORDER BY ID) ROWNUMBER,UNITPRICE,* FROM ITEMS
ORDER BY ID

SELECT ROW_NUMBER() OVER (ORDER BY UNITPRICE) ROWNUMBER,RANK() OVER (ORDER BY UNITPRICE) RANK,DENSE_RANK() OVER (ORDER BY UNITPRICE) DENSE_RANK ,UNITPRICE,* FROM ITEMS
ORDER BY 3