-- IF BLOGU
DECLARE @EXAMRESULTS   AS INT = 70
DECLARE @STATUS AS VARCHAR(20)

IF @EXAMRESULTS > 60
    SET @STATUS = 'BAŞARILI'
ELSE 
    SET @STATUS  = 'BAŞARISIZ'

SELECT @STATUS STATUS_

DECLARE @POINT AS INT 
SET @POINT = 1

IF @POINT = 1  
BEGIN
    SET @STATUS='ÇOK KÖTÜ'
    SELECT 'A'
END
IF @POINT = 2  
    SET @STATUS='KÖTÜ'
IF @POINT = 3  
    SET @STATUS='NE IYI NE KÖTÜ'
IF @POINT = 4  
    SET @STATUS='İYİ'
IF @POINT = 5  
    SET @STATUS='ÇOK İYİ'

SELECT @POINT ,@STATUS

-- CASE WHEN 
SELECT T.AGEGROUP , COUNT(*)  FROM 
(SELECT 
CASE 
WHEN AGE<35 THEN 'GENÇ'
WHEN AGE BETWEEN 36 AND 55 THEN 'ORTA YAŞLI'
WHEN AGE>55 THEN 'YAŞLI'
END AS AGEGROUP ,*
FROM CUSTOMERS) T GROUP BY T.AGEGROUP

SELECT * FROM CUSTOMERS
UPDATE  CUSTOMERS SET AGE = DATEDIFF(YEAR,BIRTHDATE,GETDATE())

-- IIF BLOGU

SELECT 
IIF(CUSTOMERGENDER='E','ERKEK','KADIN') , COUNT(*) FROM SALES
GROUP BY CUSTOMERGENDER

-- ALISTIRMA 1 
DECLARE @CITY AS VARCHAR(100)='ANKARA'
DECLARE @MONTH AS INT = 1
DECLARE @BEGDATE AS DATETIME 
DECLARE @ENDDATE AS DATETIME

IF @CITY IS NULL
    SET @CITY ='%'

IF (@BEGDATE IS NULL AND @ENDDATE IS NULL)
    BEGIN 
    SET @BEGDATE = DATEFROMPARTS(2019,@MONTH,1)
    SET @ENDDATE = DATEADD(MONTH,1,@BEGDATE)
    END
SELECT DATEPART(MONTH,DATE_) MONTH_,CITY,SUM(TOTALPRICE) FROM SALES  WHERE DATE_ BETWEEN @BEGDATE AND @ENDDATE  AND CITY LIKE @CITY AND DATEPART(MONTH,DATE_)=@MONTH
GROUP BY DATEPART(MONTH,DATE_),CITY

-- ALISTIRMA 2 
DECLARE @TOTALPRICE AS FLOAT
DECLARE @AVGPRICE AS FLOAT
SELECT @TOTALPRICE=SUM(TOTALPRICE) FROM SALES 
 SET @AVGPRICE= @TOTALPRICE / 81

-- IIF ILE COZUM
SELECT CITY , SUM(TOTALPRICE),IIF(SUM(TOTALPRICE)>@AVGPRICE,'ORTALAMANIN USTUNDE','ORTALAMANIN ALTINDA') FROM SALES
GROUP BY CITY

-- CASE WHEN ILE COZUM 
SELECT CITY , SUM(TOTALPRICE),
CASE
WHEN SUM(TOTALPRICE)>@AVGPRICE THEN 'ORTALAMANIN USTUNDE'
ELSE 'ORTALAMANIN ALTINDA'
END
FROM SALES
GROUP BY CITY

-- ALISTIRMA 3 

SELECT
 CASE 
    WHEN DATEPART(MONTH,DATE_) = 1 THEN '01.OCK'
    WHEN DATEPART(MONTH,DATE_) = 2 THEN '02.SUB'
    WHEN DATEPART(MONTH,DATE_) = 3 THEN '03.MAR'
    WHEN DATEPART(MONTH,DATE_) = 4 THEN '04.NIS'
    WHEN DATEPART(MONTH,DATE_) = 5 THEN '05.MAY'
    WHEN DATEPART(MONTH,DATE_) = 6 THEN '06.HAZ'
    WHEN DATEPART(MONTH,DATE_) = 7 THEN '07.TEM'
    WHEN DATEPART(MONTH,DATE_) = 8 THEN '08.AGU'
    WHEN DATEPART(MONTH,DATE_) = 9 THEN '09.EYL'
    WHEN DATEPART(MONTH,DATE_) = 10 THEN '10.EKI'
    WHEN DATEPART(MONTH,DATE_) = 11 THEN '11.KAS'
    WHEN DATEPART(MONTH,DATE_) = 12 THEN '12.ARA'
END AS MONTHNAME
 ,
 ROUND(SUM(TOTALPRICE),0) FROM SALES GROUP BY DATEPART(MONTH,DATE_) ORDER BY 1