ALTER PROCEDURE SPSALES
@CITY AS VARCHAR(100)=NULL,
@BEGDATE AS DATE=NULL,
@ENDDATE AS DATE = NULL
AS
    SET LANGUAGE TURKISH
    IF @CITY IS NULL
    SET @CITY='%'
    IF @BEGDATE IS NULL
    SET @BEGDATE = '2019-02-01'
    IF @ENDDATE IS NULL 
    SET @ENDDATE = '2019-03-01'

IF DATEDIFF(DAY,@BEGDATE,@ENDDATE) > 90
  BEGIN
  RAISERROR('BASLANGIC VE BITIS TARIHLERI ARASI 90 GUNDEN FAZLA OLAMAZ',16,1)
  RETURN
  END


SELECT * FROM SALES
WHERE CITY LIKE @CITY
AND DATE_ BETWEEN @BEGDATE AND @ENDDATE ORDER BY DATE_

SELECT DATEPART(MONTH,DATE_) MONTHNR,
 DATENAME(MONTH,DATE_) MONTHNAME,
SUM(TOTALPRICE) TOTALSALE FROM SALES
WHERE CITY LIKE @CITY
AND DATE_ BETWEEN @BEGDATE AND @ENDDATE 
GROUP BY DATEPART(MONTH,DATE_),DATENAME(MONTH,DATE_)
ORDER BY 1


-- BIRDEN FAZLA PARAMETRE GONDERME

EXEC SPSALES 'İSTANBUL','2019-04-01','2019-05-01'
EXEC SPSALES @CITY='İSTANBUL',@BEGDATE='2019-04-01',@ENDDATE='2019-05-01'

-- PARAMETRE GONDERMEZSEK VERDIGIMIZ DEFAULT DEGER CALISIR 
EXEC SPSALES @BEGDATE='2019-04-01',@ENDDATE='2019-05-01'

-- IF KONTROLLERI SAYESINDE DEGER GIRMEZSEK DE DEFAULT DEGER ATIYOR VE SONUC DONDURUYOR
EXEC SPSALES @CITY='B%' ,@BEGDATE='2019-01-01', @ENDDATE='2019-12-31'

TRUNCATE TABLE RESULT 
INSERT INTO RESULT 
EXEC SPSALES @BEGDATE='2019-04-01',@ENDDATE='2019-05-01',@CITY='%'

SELECT CITY,SUM(TOTALPRICE) FROM RESULT
WHERE CATEGORY1='GIDA' AND REGION='MARMARA'
GROUP BY CITY
