-- ALISTIRMA 1 

CREATE PROC SPLOGIN 
@USERNAME VARCHAR(50)='',
@EMAIL VARCHAR(100)='',
@PASSWORD VARCHAR(100),
@IPADDRESS VARCHAR(20)
AS
DECLARE @LOGINTYPE AS INT
DECLARE @USERID AS INT
IF @USERNAME <> ''
BEGIN 
       SELECT @USERID = ID FROM USERS WHERE  USERNAME_ =@USERNAME AND PASSWORD_ = @PASSWORD 
       IF @USERID IS NOT NULL
       BEGIN
       SET @LOGINTYPE = 1
       END
       ELSE
         BEGIN
              SET @LOGINTYPE = 0
         END

         INSERT INTO USERLOGIN_LOG (USERID,USERNAME,LOGINTYPE,IPADDRESS,DATE_)
         VALUES (@USERID,@USERNAME,@LOGINTYPE,@IPADDRESS,GETDATE())
END

IF @EMAIL <> ''
BEGIN 
       SELECT @USERID = ID FROM USERS WHERE  USERNAME_ =@USERNAME AND PASSWORD_ = @PASSWORD 
       IF @USERID IS NOT NULL
       BEGIN
       SET @LOGINTYPE = 1
       END
       ELSE
       BEGIN
              SET @LOGINTYPE = 0
       END

         INSERT INTO USERLOGIN_LOG (USERID,USERNAME,LOGINTYPE,IPADDRESS,DATE_)
         VALUES (@USERID,@EMAIL,@LOGINTYPE,@IPADDRESS,GETDATE())

END
--  2 E_SELIM	xpais	Emirhan SELİM	E_SELIM@sqlegitimbtk.com	E	1993-01-21	2018-07-28 01:35:35.000	(543)9894233	(534)8242021
SELECT * FROM USERS
EXEC SPLOGIN @USERNAME='E_SELIM' , @PASSWORD = 'xpais',@IPADDRESS='110.25.62.36'
EXEC SPLOGIN @USERNAME='E_SELIM@sqlegitimbtk.com', @PASSWORD = 'xpais',@IPADDRESS='110.25.62.36'

SELECT * FROM USERLOGIN_LOG

-- ALISTIRMA 2 

ALTER PROC GETCATEGORYSALES
@CITIES VARCHAR(100)='İSTANBUL,ANKARA',
@BEGDATE DATE = '2019-04-01',
@ENDDATE DATE = '2019-05-01'

AS 
DECLARE @PARAMETERS AS VARCHAR(100)
SET @PARAMETERS = '@CITIES='+@CITIES
SET @PARAMETERS = @PARAMETERS+' @BEGDATE='+CONVERT(VARCHAR,@BEGDATE,104)
SET @PARAMETERS = @PARAMETERS+' @ENDDATE='+CONVERT(VARCHAR,@ENDDATE,104)

SELECT @PARAMETERS AS PARAMETERS
SELECT CATEGORY1,SUM(TOTALPRICE) FROM SALES WHERE CITY IN (SELECT VALUE FROM STRING_SPLIT(@CITIES,',')) AND DATE_ BETWEEN @BEGDATE AND @ENDDATE
GROUP BY CATEGORY1
ORDER BY CATEGORY1


EXEC GETCATEGORYSALES

EXEC GETCATEGORYSALES @CITIES='İSTANBUL,ANKARA', @BEGDATE='2019-04-01' ,@ENDDATE = '2019-05-02'


-- ALISTIRMA 3 
CREATE PROC COMMENTSEARCH
@STRTOSEARCH  VARCHAR(100),
@BEGDATE DATE,
@ENDDATE DATE
AS 
BEGIN 

DECLARE @PARAMETERS AS VARCHAR(100)
DECLARE @USERNAME AS VARCHAR(100)
DECLARE @HOSTNAME AS  VARCHAR(100)
DECLARE @LOGDATE AS DATETIME
DECLARE @LOGENDDATE AS DATETIME
DECLARE @DURATION AS INT
DECLARE @ROWCOUNT AS INT

SET @USERNAME = SUSER_NAME()
SET @HOSTNAME = HOST_NAME()
SET @LOGDATE = GETDATE()

SET @PARAMETERS = '@STRTOSEARCH='+@STRTOSEARCH
SET @PARAMETERS = @PARAMETERS+' @BEGDATE='+CONVERT(VARCHAR,@BEGDATE,104)
SET @PARAMETERS = @PARAMETERS+' @ENDDATE='+CONVERT(VARCHAR,@ENDDATE,104)


SELECT @PARAMETERS

SELECT * FROM COMMENTS WHERE TEXT LIKE '%'+ @STRTOSEARCH + '%'
AND CREATIONDATE BETWEEN @BEGDATE AND @ENDDATE
SET @ROWCOUNT = @@ROWCOUNT

SET @LOGENDDATE = GETDATE()
SET @DURATION = DATEDIFF(SECOND,@ENDDATE,@LOGENDDATE)

INSERT INTO PROCEDURELOG (USERNAME_,HOSTNAME,SPNAME,PARAMETERS,BEGDATE,ENDDATE,DURATION,ROWCOUNT_)
VALUES (@USERNAME ,@HOSTNAME,'COMMENT SEARCH',@PARAMETERS,@LOGDATE,@LOGENDDATE,@DURATION,@ROWCOUNT)

END

EXEC COMMENTSEARCH 'SQL SERVER','20100101','20100131'

-- ALISTIRMA 4 19.00 DA BAŞLADIN

ALTER PROC GETMONTHLYSALES
AS
BEGIN
SELECT C.CITY,I.CATEGORY1,DATEPART(MONTH,DATE_) MONTHNR,DATENAME(MONTH,DATE_) MONTHNAME,SUM(OD.LINETOTAL) TOTALSALE FROM ORDERS O JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID JOIN ITEMS I ON OD.ITEMID=I.ID JOIN ADDRESS A ON A.ID=O.ADDRESSID JOIN CITIES C ON C.ID=A.CITYID
GROUP BY C.CITY,I.CATEGORY1,DATEPART(MONTH,DATE_)
,DATENAME(MONTH,DATE_) ORDER BY 1,2,DATEPART(MONTH,DATE_)

END


EXEC GETMONTHLYSALES

CREATE TABLE #T(CITY VARCHAR(50),CATEGORY1 VARCHAR(50),MONTHNR  INT,MONTHNAME VARCHAR(20),TOTALSALE FLOAT)
DROP TABLE #T
INSERT INTO #T 
EXEC GETMONTHLYSALES

SELECT DISTINCT CITY ,CATEGORY1,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND CITY=T.CITY AND MONTHNR=1) OCAK,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND CITY=T.CITY AND MONTHNR=2) SUBAT,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND CITY=T.CITY AND MONTHNR=3) MART,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND CITY=T.CITY AND MONTHNR=4) NISAN,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND CITY=T.CITY AND MONTHNR=5) MAYIS,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND CITY=T.CITY AND MONTHNR=6) HAZIRAN,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND CITY=T.CITY AND MONTHNR=7) TEMMUZ,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND CITY=T.CITY AND MONTHNR=8) AGUSTOS,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND CITY=T.CITY AND MONTHNR=9) EYLUL,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND CITY=T.CITY AND MONTHNR=10) EKIM,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND CITY=T.CITY AND MONTHNR=11) KASIM,
(SELECT TOTALSALE FROM #T WHERE CATEGORY1=T.CATEGORY1 AND CITY=T.CITY AND MONTHNR=12) ARALIK
 FROM #T T
WHERE CATEGORY1='GIDA' 
