--ASCI FONKSIYONU 
SELECT ASCII('T')
SELECT ASCII(1)
SELECT ASCII(2)

-- CHAR FONKSIYONU 
-- ICINE ASCI KODU GIRINCE O ASCI KODUNUN NORMALDE OLAN DEGERİNİ VERİR
SELECT CHAR(84)
SELECT CHAR(49)
SELECT CHAR(50)

-- CONCAT FONKSIYONU 
-- CONCAT ICINE GIRILEN DEGERLERI TEK COLUMN DA BIRLESTIRIR  
SELECT CONCAT('TURKCELL ','GELECEGI ','YAZANLAR ')
-- BU ALT SATIRDAKI DE AYNI ISI GORUR AMA HER ZAMAN KULLANILMAZ USTTEKI KOLAY VE KULLANISLI OLAN 
SELECT 'TURKCELL ' + 'GELECEGI ' + 'YAZANLAR '

-- LEFT ve RIGHT FONKSIYONLARI
-- SOLDAN VEYA SAGDAN BELIRTILEN SAYI KADAR KARAKTER ALIR 
SELECT LEFT('TURKCELL GELECEGI YAZANLAR',8)
SELECT RIGHT('TURKCELL GELECEGI YAZANLAR',8)

-- LTRIM , RTRIM VE TRIM FONKSIYONLARI 
-- LTRIM SOLDAKI BOSLUKLARI SILER RTRIM SAGRADKI BOSLUKLAR TRIM ISE HEM SAGDAKI HEM SOLDAKI BOSLUKLARI SILER
-- ESKI KULLANIMLAR
SELECT LTRIM(' TURKCELL GELECEGI YAZANLAR ')
SELECT RTRIM(' TURKCELL GELECEGI YAZANLAR ')
SELECT TRIM(' TURKCELL GELECEGI YAZANLAR ')

SELECT LTRIM('TURKCELL GELECEGI YAZANLAR','TURKCELL')
SELECT RTRIM('TURKCELL GELECEGI YAZANLAR','YAZANLAR')

-- YENI KULLANIMLAR 
-- LEADING KULLANIRSAK SOL TARAFTA BELIRTILEN KISIM KIRPILIR TRAILING SAG KISMI KIRPAR BOTH ISE HER IKI KISMIDA KIRPAR

SELECT TRIM(LEADING 'TURKCELL' FROM 'TURKCELL GELECEGI YAZANLAR' )
SELECT TRIM(TRAILING 'YAZANLAR' FROM 'TURKCELL GELECEGI YAZANLAR' )

SELECT TRIM(LEADING '#' FROM '#TURKCELL GELECEGI YAZANLAR#' )
SELECT TRIM(TRAILING '#' FROM '#TURKCELL GELECEGI YAZANLAR#' )
SELECT TRIM(BOTH '#' FROM '#TURKCELL GELECEGI YAZANLAR#' )
SELECT TRIM(LEADING '<B></B>' FROM '<B>TURKCELL GELECEGI YAZANLAR</B>' )
SELECT TRIM(BOTH '<B></B>' FROM '<B>TURKCELL GELECEGI YAZANLAR</B>' )


-- LOWER , UPPER ,REVERSE VE REPLICATE FONKSYONLARI

SELECT LOWER ('TURKCELL GELECEGI YAZANLAR')
SELECT UPPER('turkcell gelecegi yazanlar')
SELECT REVERSE ('TURKCELL GELECEGI YAZANLAR')
-- REPLICATE VERILERI BELLI SAYIDA YANYANA YAZAR FIS NO DA KULLANILABILIR 
-- ORNEGIN ID 136 ISE 10 BASAMAKLI OLUCAKSA 
-- 0000000136 OLMASI ICIN REPLICATE KULLANILIR
SELECT REPLICATE('SQL ',3)

-- REPLACE FONKSIYONU
SELECT  REPLACE('T-SQL İLE BIR PROGRAMLAMA DILI ILE YAPABILECEGINIZ HEMEN HEMEN HER SEYI YAOPABILIRSINIZ ','T-SQL','TRANSACT SQL')


-- SUBSTRING FONKSIYONU
SELECT SUBSTRING('SQL SERVER 2022 ILE YENI GELEN OZELLIKLERDEN BIRI DE IYILESTIRILEN TRIM FONKSIYONUDUR ',1,15)

-- CHARINDEX FONKSIYONU 
SELECT CHARINDEX('2022','SQL SERVER 2022 SÜRÜMÜ 2022 YILINDA PİYASAYA SÜRÜLMÜŞTÜR')

-- STRING_SPLIT FONKSIYONU
SELECT * FROM string_split('ISTANBUL,ANKARA,IZMIR',',',1)

-- ALIŞTIRMA 1 
UPDATE  LAB01  SET NAMESURNAME = NAME_ +' '+ SURNAME
UPDATE  LAB01  SET NAMESURNAME = CONCAT(NAME_ ,' ', SURNAME)

-- ALIŞTIRMA 2 

UPDATE LAB02 SET NAMESURNAME = NAME_+' '+ UPPER(SURNAME)
UPDATE LAB02 SET NAMESURNAME = CONCAT(NAME_,' ',UPPER(SURNAME))

-- ALIŞTIRMA 3
SELECT SUBSTRING(U.TELNR1,2,3) AS OPERATOR_NO,COUNT(*) AS TELEFONSAYISI FROM USERS  U GROUP BY SUBSTRING(U.TELNR1,2,3) ORDER BY 1

-- ALIŞTIRMA 4
SELECT ID,FILENAME,
REPLACE(INFO,'##',CHAR(13)) EXIFINFO FROM LAB04

-- ALIŞTIRMA 5 
SELECT ID,CREATIONDATE,
(SELECT COUNT(*) FROM STRING_SPLIT(TEXT,' ')) WORDCOUNT,
(SELECT COUNT(*) FROM STRING_SPLIT(TEXT,' ') WHERE VALUE LIKE '%SQL%') SQL_WORDCOUNT,
(SELECT COUNT(*) FROM STRING_SPLIT(TEXT,' ') WHERE VALUE LIKE 'SQL') SQL_WORDCOUNT2

FROM LAB05 ORDER BY ID

-- ALIŞTIRMA 6 

SELECT * FROM LAB06 

UPDATE LAB06 SET ORDERNO=FORMAT(DATE_,'YYYYMMDD') + '-'+ REPLICATE('0',8-LEN(ID)) + ID

-- ALIŞTIRMA 7
SELECT LEFT(NANE_,1)+LEFT(SURNAME,1) BASHARF ,COUNT(*) FROM LAB07 GROUP BY LEFT(NAME_,1),LEFT(SURNAME,1) ORDER BY 1

-- ALIŞTIRMA 8 
SELECT ID,NAMESURNAME ,
(
    SELECT TOP 1 VALUE FROM string_split(NAMESURNAME,' ',1) order by ordinal desc
) SURNAME FROM LAB08

UPDATE LAB08 SET NAME_=REPLACE(NAMESURNAME+' '+ SURNAME + ' ')

-- ALIŞTIRMA 9 

SELECT ID , NAME_ ,SURNAME , NAME1, 
UPPER(LEFT(NAME2,1)) +
SUBSTRING(NAME2,2,LEN(NAME2)) FROM 
(
SELECT ID,NAME_,SURNAME,NAMESURNAME,
(
    SELECT VALUE FROM STRING_SPLIT(NAME_,' ',1) WHERE ORDINAL=1 
) NAME1,
(
    SELECT VALUE FROM STRING_SPLIT(NAME_,' ',1) WHERE ORDINAL=2
) NAME2 FROM LAB09
WHERE NAME_ LIKE '% %'

) T

UPDATE LAB09 SET NAME_= (SELECT VALUE FROM STRING_SPLIT(NAME_,' ',1) WHERE ORDINAL=1) + ' '+
UPPER(LEFT(
   ( SELECT VALUE FROM STRING_SPLIT(NAME_,' ',1) WHERE ORDINAL=2)
    ,1)) +
    UPPER(
        SUBSTRING(
            (SELECT VALUE FROM STRING_SPLIT(NAME_,' ',1) WHERE ORDINAL=2 ) ,
            2,100 ))
WHERE NAME_ LIKE '% %'