-- SCALAR VALUED FUNCTIONS

-- CREATE FUNCTION DBO.TOPLA ( @SAYI1 AS INT,@SAYI2 AS INT)
-- AS
-- RETURNS INT
-- BEGIN 
-- DECLARE @SONUC AS INT
-- SET @SONUC =@SAYI1 + @SAYI2
-- RETURN @SONUC
-- END


-- CREATE FUNCTION DBO.DORTISLEM(@SAYI1 AS INT,@SAYI2 AS INT ,@ISLEM AS VARCHAR(10))
-- RETURNS FLOAT
-- AS
-- BEGIN
--     DECLARE @SONUC AS FLOAT
--     IF @ISLEM = 'TOPLA'
--     SET @SONUC= @SAYI1 + @SAYI2
--     IF @ISLEM = 'ÇARP'
--     SET @SONUC= @SAYI1 * @SAYI2
--     IF @ISLEM = 'ÇIKAR'
--     SET @SONUC= @SAYI1 - @SAYI2
--     IF @ISLEM = 'BOL'
--     SET @SONUC= @SAYI1 / CONVERT(float,@SAYI2)
--     RETURN @SONUC
-- END

-- SELECT DBO.DORTISLEM(20,30,'TOPLA')

-- CREATE FUNCTION DBO.GETMONTHNAME(@DATE AS DATETIME)
-- RETURNS VARCHAR(10)
-- BEGIN
-- DECLARE @RESULT AS VARCHAR(10)
-- IF MONTH(@DATE) = 1
--  SET @RESULT ='01OCK'
--  IF MONTH(@DATE) = 2
--  SET @RESULT ='02SUB'
--  IF MONTH(@DATE) = 3
--  SET @RESULT ='02MAR'
--  IF MONTH(@DATE) = 4
--  SET @RESULT ='04NIS'
--  IF MONTH(@DATE) = 5
--  SET @RESULT ='05MAY'
--  IF MONTH(@DATE) = 6
--  SET @RESULT ='06HAZ'
--  IF MONTH(@DATE) = 7
--  SET @RESULT ='07TEM'
--  IF MONTH(@DATE) = 8
--  SET @RESULT ='08AGU'
--  IF MONTH(@DATE) = 9
--  SET @RESULT ='08EYL'
--  IF MONTH(@DATE) = 10
--  SET @RESULT ='10EKI'
--  IF MONTH(@DATE) = 11
--  SET @RESULT ='11KAS'
--  IF MONTH(@DATE) = 12
--  SET @RESULT ='12ARA'

--  RETURN @RESULT
-- END

-- SELECT DBO.GETMONTHNAME('2022-12-1')


-- -- JOIN YONTEMI
-- SELECT I.ID , I.ITEMCODE,I.ITEMNAME,I.UNITPRICE,
-- SUM(OD.LINETOTAL), SUM(OD.AMOUNT),
-- MIN(I.UNITPRICE) MINFIYAT,MAX(I.UNITPRICE) MAXFIYAT,
-- AVG(I.UNITPRICE) ORTALAMAFIYAT
--   FROM ITEMS I JOIN ORDERDETAILS OD ON OD.ITEMID= I.ID
--   GROUP BY I.ID , I.ITEMCODE,I.ITEMNAME,I.UNITPRICE

--   -- SUBQUERY YONTEMI
-- SELECT I.ID , I.ITEMCODE,I.ITEMNAME,I.UNITPRICE,
-- (SELECT SUM(OD.LINETOTAL)  FROM ORDERDETAILS OD WHERE OD.ITEMID=I.ID) TOPLAMCIRO,(SELECT  SUM(OD.AMOUNT) FROM ORDERDETAILS OD WHERE OD.ITEMID = I.ID) TOPLAMMIKTAR
--   FROM ITEMS I
--  ORDER BY 1

-- FONKSIYON YONTEMI

-- CREATE FUNCTION DBO.GETITEMSALES(@ITEMID AS INT)
--  RETURNS  FLOAT
--  AS 
--  BEGIN
--     DECLARE @RESULT AS FLOAT
--     SELECT @RESULT = SUM(LINETOTAL)
--     FROM ORDERDETAILS
--     WHERE ITEMID=@ITEMID
--     RETURN @RESULT
--  END


-- CREATE FUNCTION DBO.GETITEMSALES_AMOUNT(@ITEMID AS INT)
--  RETURNS  FLOAT
--  AS 
--  BEGIN
--     DECLARE @RESULT AS FLOAT
--     SELECT @RESULT = SUM(AMOUNT)
--     FROM ORDERDETAILS
--     WHERE ITEMID=@ITEMID
--     RETURN @RESULT
--  END

-- FONKSIYON KULLANIMI
-- SCALER VALUED FUNCTIONS

-- SELECT I.ID , I.ITEMCODE, I.ITEMNAME, I.UNITPRICE,
--     DBO.GETITEMSALES(I.ID), DBO.GETITEMSALES_AMOUNT(I.ID)
-- FROM ITEMS I  

-- CREATE FUNCTION DBO.GETITEMSALES_MINPRICE(@ITEMID AS INT)
--  RETURNS  FLOAT
--  AS 
--  BEGIN
--     DECLARE @RESULT AS FLOAT
--     SELECT @RESULT = MIN(UNITPRICE)
--     FROM ORDERDETAILS
--     WHERE ITEMID=@ITEMID
--     RETURN @RESULT
--  END

-- CREATE FUNCTION DBO.GETITEMSALES_MAXPRICE(@ITEMID AS INT)
--  RETURNS  FLOAT
--  AS 
--  BEGIN
--     DECLARE @RESULT AS FLOAT
--     SELECT @RESULT = MAX(UNITPRICE)
--     FROM ORDERDETAILS
--     WHERE ITEMID=@ITEMID
--     RETURN @RESULT
--  END


-- ALTER FUNCTION DBO.GETITEMSALES_AVGPRICE(@ITEMID AS INT)
--  RETURNS  FLOAT
--  AS 
--  BEGIN
--     DECLARE @RESULT AS FLOAT
--     SELECT @RESULT = AVG(UNITPRICE)
--     FROM ORDERDETAILS
--     WHERE ITEMID=@ITEMID
--     RETURN @RESULT
--  END


-- SELECT I.ID , I.ITEMCODE, I.ITEMNAME, I.UNITPRICE,
--     DBO.GETITEMSALES(I.ID), DBO.GETITEMSALES_AMOUNT(I.ID),
--     DBO.GETITEMSALES_MINPRICE(I.ID) MINPRICE ,
--         DBO.GETITEMSALES_MAXPRICE(I.ID) MAXPRICE ,
--             DBO.GETITEMSALES_AVGPRICE(I.ID)
-- FROM ITEMS I  

-- TABLE VALUED FUNCTION YONTEMI

-- CREATE FUNCTION DBO.FNITEMINFO(@ITEMID AS INT)
-- RETURNS TABLE
-- AS RETURN(
--     SELECT  I.ITEMCODE,I.ITEMNAME,SUM(OD.LINETOTAL) TOTALSALE,
--     SUM(OD.AMOUNT) TOTALAMOUNT,MIN(OD.UNITPRICE) MINPRICE,MAX(OD.UNITPRICE) MAXPRICE,
--     AVG(OD.UNITPRICE) AVGPRICE FROM ITEMS I JOIN ORDERDETAILS OD ON OD.ITEMID = I.ID 
--     GROUP BY I.ITEMCODE,I.ITEMNAME

-- )

SELECT I.ID , I.ITEMCODE, I.ITEMNAME, I.UNITPRICE,
INFO.TOTALSALE TOPLAMCIRO,INFO.TOTALAMOUNT TOPLAMADET,INFO.MINPRICE ENDUSUKFIYAT,
INFO.MAXPRICE ENYUKSEKFIYAT,INFO.AVGPRICE ORTALAMAFIYAT

FROM ITEMS I 
CROSS APPLY (SELECT * FROM DBO.FNITEMINFO(I.ID)) INFO
ORDER BY 1

SELECT * FROM DBO.FNITEMINFO(2)