-- VIEW OLUSTURMA
-- CREATE VIEW VWORDERS AS 
-- ALTER VIEW VWORDERS AS 

-- SELECT 
-- O.ID ORDERID,O.DATE_ TARIH,
-- CASE 
--     WHEN MONTH(O.DATE_) =1 THEN '01.OCK'
--     WHEN MONTH(O.DATE_) =2 THEN '02.SUB'
--     WHEN MONTH(O.DATE_) =3 THEN '03.MAR'
--     WHEN MONTH(O.DATE_) =4 THEN '04.NIS'
--     WHEN MONTH(O.DATE_) =5 THEN '05.MAY'
--     WHEN MONTH(O.DATE_) =6 THEN '06.HAZ'
--     WHEN MONTH(O.DATE_) =7 THEN '07.TEM'
--     WHEN MONTH(O.DATE_) =8 THEN '08.AGU'
--     WHEN MONTH(O.DATE_) =9 THEN '09.EYL'
--     WHEN MONTH(O.DATE_) =10 THEN '10.EKI'
--     WHEN MONTH(O.DATE_) =11 THEN '11.KAS'
--     WHEN MONTH(O.DATE_) =12 THEN '12.ARA'


--     END AS AY
--     ,
-- U.USERNAME_ KULLANICIADI,U.NAMESURNAME ADSOYAD,U.GENDER CINSIYET,U.BIRTHDATE DOGUMTARIHI ,
-- C.CITY SEHIR,T.TOWN ILCE,D.DISTRICT MAHALLE,A.ADDRESSTEXT ACIKADRESS,I.ITEMCODE,I.ITEMNAME URUNADI,I.BRAND MARKA,I.CATEGORY1,I.CATEGORY2,
-- I.CATEGORY3,I.UNITPRICE URUNBIRIMFIYAT,OD.AMOUNT MIKTAR,OD.UNITPRICE BIRIMFIYAT,OD.LINETOTAL TUTAR
-- FROM ORDERS O 
-- JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
-- JOIN ITEMS I ON I.ID=OD.ITEMID
-- JOIN USERS U ON U.ID = O.USERID
-- JOIN ADDRESS A ON A.ID =O.ADDRESSID
-- JOIN CITIES C ON C.ID=A.CITYID
-- JOIN TOWNS T ON T.ID = A.TOWNID
-- JOIN DISTRICTS D ON D.ID=A.DISTRICTID


-- SELECT SEHIR,SUM(TUTAR) FROM VWORDERS GROUP BY SEHIR ORDER BY 2 DESC

-- EN ÇOK SATANLAR VIEW I 
-- CREATE VIEW BESTSELLER40 
-- AS 
-- SELECT TOP 40 I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,
-- SUM(OD.AMOUNT) TOTALAMOUNT,SUM(OD.LINETOTAL) TOTALSALE
--  FROM ITEMS I JOIN ORDERDETAILS OD ON I.ID= OD.ITEMID GROUP BY I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3 
--  ORDER BY SUM(OD.LINETOTAL) DESC

-- ALISTIRMA 1

--  CREATE VIEW VWMONTHLYSALES AS
--  SELECT C.CITY SEHIR,MONTH(O.DATE_) AY,SUM(O.TOTALPRICE) TOPLAMTUTAR FROM CITIES C JOIN ADDRESS A ON A.CITYID = C.ID JOIN ORDERS O ON O.ADDRESSID=A.ID 
--  GROUP BY MONTH(O.DATE_),C.CITY

--  SELECT SEHIR , AY,TOPLAMTUTAR FROM VWMONTHLYSALES ORDER BY SEHIR,AY

-- ALISTIRMA 2

-- CREATE VIEW  VWLASTORDER
-- AS
--     SELECT C.CITY SEHIR, LASTORDER.NAMESURNAME SON_MUSTERI, LASTORDER.DATE_ SON_SIPARIS_TARIHI, LASTORDER.TOTALPRICE SON_TUTAR
--     FROM CITIES C
--     CROSS APPLY (
--     SELECT TOP 1
--             U.NAMESURNAME, O.DATE_, O.TOTALPRICE
--         FROM ORDERS O JOIN USERS U ON U.ID = O.USERID JOIN ADDRESS A ON A.ID=O.ADDRESSID
--         WHERE A.CITYID=C.ID
--         ORDER BY O.DATE_ DESC )  LASTORDER  


-- ALISTIRMA 3 23.05 TE BAŞLADIN

--     CREATE VIEW  VWITEMINFO
--     AS
--     SELECT I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.BRAND MARKA,I.UNITPRICE BIRIMFIYAT,I.CATEGORY1 CATEGORY1,I.CATEGORY2 CATEGORY2 ,I.CATEGORY3 CATEGORY3 , SUM(OD.LINETOTAL) TOPLAMCIRO ,SUM(OD.AMOUNT) TOPLAMMIKTAR , SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) ORTALAMAFIYAT ,
--     SUM(OD.LINETOTAL)/
--     (SELECT SUM(OD.LINETOTAL) FROM ORDERDETAILS OD WHERE OD.ITEMID IN (SELECT ID FROM ITEMS I1 WHERE CATEGORY1 = I.CATEGORY1) ) KATEGORI1ORAN ,
--     SUM(OD.LINETOTAL)/
--     (SELECT SUM(OD.LINETOTAL) FROM ORDERDETAILS OD WHERE OD.ITEMID IN (SELECT ID FROM ITEMS I1 WHERE CATEGORY2 = I.CATEGORY2) ) KATEGORI2ORAN ,
--     SUM(OD.LINETOTAL)/
--     (SELECT SUM(OD.LINETOTAL) FROM ORDERDETAILS OD WHERE OD.ITEMID IN (SELECT ID FROM ITEMS I1 WHERE CATEGORY3 = I.CATEGORY3) ) KATEGORI3ORAN ,
--     SUM(OD.LINETOTAL)/
--     (SELECT SUM(OD.LINETOTAL) FROM ORDERDETAILS OD WHERE OD.ITEMID IN (SELECT ID FROM ITEMS I1 WHERE BRAND = I.BRAND) ) MARKAORAN 

--   FROM ORDERDETAILS OD JOIN ITEMS I ON I.ID=OD.ITEMID GROUP BY I.ITEMCODE,I.ITEMNAME ,I.BRAND ,I.UNITPRICE ,I.CATEGORY1 ,I.CATEGORY2  ,I.CATEGORY3 
  


-- SELECT * FROM VWITEMINFO WHERE CATEGORY1='KOZMETIK'
-- SELECT * FROM VWITEMINFO WHERE MARKA='ULKER' ORDER BY TOPLAMCIRO DESC

