CREATE DATABASE TEST

CREATE TABLE CUSTOMERS (
    ID INT IDENTITY PRIMARY KEY,
    NAMESURNAME VARCHAR(50),
    GENDER VARCHAR(1),
    BIRTHDATE DATE,
    CITY VARCHAR(50),
    TOWN VARCHAR(50),
    TELNR VARCHAR(15),
    TCNUMBER VARCHAR(11),
    hfsdjh 

)
DROP TABLE CUSTOMERS2
ALTER TABLE CUSTOMERS ADD PRIMARY KEY (ID)
ALTER TABLE CUSTOMERS ALTER COLUMN NAMESURNAME NVARCHAR(50) NOT NULL
ALTER TABLE CUSTOMERS  ADD  AGE INT
ALTER TABLE CUSTOMERS ALTER COLUMN AGE TINYINT
ALTER TABLE CUSTOMERS ADD AGEGROUP VARCHAR(20)
ALTER TABLE CUSTOMERS ADD ID2 INT IDENTITY(1,1) 
ALTER TABLE CUSTOMERS DROP COLUMN AGEGROUP,AGE

SELECT * FROM CUSTOMERS
INSERT INTO CUSTOMERS (NAMESURNAME,GENDER,BIRTHDATE,CITY,TOWN,TELNR,TCNUMBER) VALUES ('ÖMER FARUK','E','1990-01-01','ÇANAKKALE','BİGA','05321234567','12345678901')
TRUNCATE TABLE CUSTOMERS
DELETE FROM CUSTOMERS
DROP TABLE CUSTOMERS
