-- CREATE DATABASE TEST
-- CREATE TABLE CUSTOMERS(
--     ID INT IDENTITY(1,1) PRIMARY KEY,
--     NAMESURNAME VARCHAR(100) NOT NULL,
--     GENDER VARCHAR(1),
--     BIRTHDATE DATE ,
--     CITY VARCHAR(50),
--     TOWN VARCHAR(50),
--     TELNR VARCHAR(15),
--     TCNO VARCHAR(11)
-- )

-- ALTER TABLE CUSTOMERS ADD PRIMARY KEY (ID)
ALTER TABLE CUSTOMERS ADD AGE INT
ALTER TABLE CUSTOMERS ADD AGEGROUP VARCHAR(20)
ALTER TABLE CUSTOMERS ALTER COLUMN NAMESURNAME VARCHAR(100)
ALTER TABLE CUSTOMERS ALTER COLUMN GENDER VARCHAR(10)
ALTER TABLE CUSTOMERS DROP COLUMN AGEGROUP

CREATE DATABASE TEST1
DROP DATABASE TEST1

DROP TABLE CUSTOMERS 

SELECT * FROM CUSTOMERS
INSERT INTO CUSTOMERS (NAMESURNAME,GENDER,BIRTHDATE,CITY,TOWN,TELNR,TCNO) VALUES ('ÖMER FARUK','E','1990-01-01','ÇANAKKALE','BIGA','05321234567','12345678901')
TRUNCATE TABLE CUSTOMERS
DELETE FROM CUSTOMERS
DROP TABLE CUSTOMERS

--ALIŞTIRMA 1 
