SELECT * FROM CUSTOMERS
SELECT DISTINCT CITY FROM CUSTOMERS
SELECT DISTINCT CITY,TOWN FROM CUSTOMERS 

SELECT * FROM CUSTOMERS ORDER BY NAMESURNAME
SELECT * FROM CUSTOMERS ORDER BY CITY,TOWN,NAMESURNAME DESC
SELECT * FROM CUSTOMERS ORDER BY 5,6 DESC
SELECT * FROM CUSTOMERS ORDER BY BIRTHDATE
SELECT * FROM CUSTOMERS ORDER BY AGE DESC

SELECT TOP 10 * FROM CUSTOMERS ORDER BY BIRTHDATE
SELECT TOP 50 PERCENT * FROM CUSTOMERS ORDER BY BIRTHDATE DESC

SELECT C.ID MUSTERINO,C.NAMESURNAME AS ADSOYAD,C.GENDER CINSIYET,C.BIRTHDATE DOGUMTARIHI,C.CITY SEHIR,C.TOWN ILCE FROM CUSTOMERS AS C ORDER BY SEHIR,ILCE,ADSOYAD

SELECT DISTINCT  CITY FROM CUSTOMERS
SELECT DISTINCT CITY , TOWN FROM CUSTOMERS WHERE CITY='ÇANAKKALE'
UPDATE CUSTOMERS SET AGE = NULL
UPDATE CUSTOMERS SET AGE= DATEDIFF(YEAR,BIRTHDATE,GETDATE())
SELECT DISTINCT CITY,AGE FROM CUSTOMERS WHERE CITY='ÇANAKKALE'

SELECT * FROM CUSTOMERS ORDER BY ID
SELECT * FROM CUSTOMERS ORDER BY ID DESC
SELECT * FROM CUSTOMERS ORDER BY NAMESURNAME
SELECT * FROM CUSTOMERS ORDER BY CITY , TOWN 
SELECT * FROM CUSTOMERS WHERE CITY='ÇANAKKALE' ORDER BY AGE
SELECT * FROM CUSTOMERS WHERE CITY='ÇANAKKALE' ORDER BY BIRTHDATE
SELECT C.ID MUSTERINO,C.NAMESURNAME ADSOYAD,C.GENDER CINSIYET,C.BIRTHDATE DOGUMTARIHI FROM CUSTOMERS C ORDER BY C.CITY , C.TOWN

SELECT TOP 10 * FROM CUSTOMERS ORDER BY BIRTHDATE
SELECT TOP 10 * FROM CUSTOMERS ORDER BY BIRTHDATE DESC
SELECT TOP 10 * FROM CUSTOMERS WHERE GENDER='KADIN' ORDER BY AGE
SELECT TOP 10 PERCENT * FROM CUSTOMERS WHERE GENDER='ERKEK' ORDER BY AGE DESC
SELECT TOP 5 * FROM CUSTOMERS WHERE GENDER='ERKEK' AND NAMESURNAME LIKE 'F%' ORDER BY BIRTHDATE
