select * from CUSTOMERS
select NAMESURNAME , GENDER , BIRTHDATE FROM CUSTOMERS
insert into CUSTOMERS ( NAMESURNAME ,GENDER ,BIRTHDATE,CITY,TOWN,TELNR,TCNUMBER) VALUES ('Ömer faruk Tulum','E','2004-10-24','Çanakkale','Biga','5331234567','12345678912')
select [NAMESURNAME],[GENDER],[BIRTHDATE],[CITY],[TOWN],[TELNR],[TCNUMBER] from CUSTOMERS

select * from CUSTOMERS
TRUNCATE TABLE CUSTOMERS
SET IDENTITY_INSERT CUSTOMERS ON
INSERT INTO CUSTOMERS (ID,NAMESURNAME,GENDER,BIRTHDATE,CITY,TOWN,TELNR,TCNUMBER) VALUES (1,'CEM ARSLAN','E','1967-01-25','AYDIN','ÇİNE','XXX63312XXX','XX0024783XX')

SELECT * FROM CUSTOMERS
UPDATE CUSTOMERS SET GSMOPERATOR='TURKCELL'

SELECT * FROM CUSTOMERS
UPDATE CUSTOMERS SET AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())
UPDATE CUSTOMERS SET GSMOPERATOR=NULL , AGE=NULL
UPDATE CUSTOMERS SET GSMOPERATOR='TURKCELL' , AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())

insert into CUSTOMERS (ID, NAMESURNAME,GENDER ,BIRTHDATE,CITY,TOWN) VALUES (4,'Faruk Tulum','E','2004-10-25','Çanakkale','LAPSEKİ')

