SELECT COUNT(*) FROM SALES
SELECT * FROM SALES ORDER BY AMOUNT 
SELECT * FROM SALES ORDER BY AMOUNT DESC

SELECT COUNT(*) SATIRSAYISI ,
SUM(AMOUNT) TOPLAMADET,SUM(TOTALPRICE) TOPLAMFIYAT,
AVG(AMOUNT) ORTALAMAADET,AVG(TOTALPRICE) ORTALAMAFIYAT,
MIN(AMOUNT) MINIMUMADET,MIN(TOTALPRICE) MINIMUMFIYAT,
MAX(AMOUNT) MAXIMUMADET,MAX(TOTALPRICE) MAXIMUMFIYAT FROM SALES WHERE CITY='ANKARA'


select * from SALES where CATEGORY1='GIDA' AND CITY='İSTANBUL'
SELECT SUM(AMOUNT) AS TOTALAMOUNT , SUM(TOTALPRICE) AS SUMTOTALPRICE , COUNT(*) AS ROW_COUNT ,
 AVG(TOTALPRICE) AS ORTALAMASATIS ,MIN(DATE_) AS MINDATE , MAX(DATE_) AS MAXDATE FROM SALES WHERE CATEGORY1 = 'GIDA' AND CITY='İSTANBUL'
 SELECT COUNT( DISTINCT CUSTOMERCODE) AS ERKEKMUSTERISAYISI  FROM SALES WHERE CUSTOMERGENDER='E'
  SELECT COUNT( DISTINCT CUSTOMERCODE) AS KADIN  FROM SALES WHERE CUSTOMERGENDER='K'
  SELECT COUNT(DISTINCT CUSTOMERCODE) AS SSS FROM SALES WHERE CUSTOMERGENDER='E'

  select CITY,count(*) TOPLAMSATIR , sum(TOTALPRICE) TOPLAMSATIS from SALES WHERE CITY IN ('İSTANBUL','ANKARA') GROUP BY CITY
  SELECT * FROM SALES
  SELECT CITY , COUNT(AMOUNT) TOPLAMMIKTAR , SUM(TOTALPRICE) TOPLAMSATIS FROM SALES WHERE CITY IN ('İSTANBUL','ANKARA') GROUP BY CITY
  SELECT CITY , COUNT(TOTALPRICE) FROM SALES WHERE CITY IN ('İSTANBUL','ANKARA') GROUP BY CITY
  SELECT CITY , MIN(TOTALPRICE) MINSATIS , MAX(TOTALPRICE) MAXSATIS  FROM SALES WHERE CITY IN ('İSTANBUL','ANKARA') AND CATEGORY1='GIDA' GROUP BY CITY
  SELECT COUNT(*) FROM SALES
  SELECT AVG(PRICE) FROM SALES
  SELECT MIN(DATE_) ILKTARIH , MAX(DATE_) SONTARIH FROM SALES 

  SELECT CITY SEHIR , SUM(TOTALPRICE) TOPLAMSATIS , SUM(AMOUNT) TOPLAMMIKTAR FROM SALES GROUP BY CITY ORDER BY TOPLAMSATIS DESC
  SELECT CITY SEHIR , CONVERT(DATE,DATE_) TARIH , SUM(TOTALPRICE) FROM SALES  WHERE CITY ='İSTANBUL'  GROUP BY CITY,CONVERT(DATE,DATE_) ORDER BY TARIH
  SET LANGUAGE TURKISH
  SELECT  DATENAME(DW,DATE_) TARIH , SUM(TOTALPRICE) TOPLAMSATIS FROM SALES WHERE CITY='İSTANBUL' GROUP BY DATEPART(DW,DATE_),  DATENAME(WEEKDAY,DATE_)  ORDER BY DATEPART(DW,DATE_)

SELECT CATEGORY1 ,CATEGORY2 , SUM(TOTALPRICE) TOPLAMSATIS FROM SALES GROUP BY CATEGORY1,CATEGORY2 ORDER BY 1, 3 DESC
SELECT CITY SEHIR , SUM(TOTALPRICE) TOPLAMSATIS FROM SALES WHERE REGION='MARMARA' GROUP BY CITY HAVING SUM(TOTALPRICE) >200000 ORDER BY TOPLAMSATIS DESC
SELECT CITY SEHIR ,  COUNT(DISTINCT CUSTOMERCODE) TOPLAMMUSTERI , SUM(TOTALPRICE) TOPLAMSATIS , SUM(TOTALPRICE)/COUNT(DISTINCT CUSTOMERCODE) ORTALAMASATIS FROM SALES WHERE REGION='MARMARA' GROUP BY CITY HAVING COUNT(DISTINCT CUSTOMERCODE) > 1000

-- SELECT * FROM CUSTOMERS
-- SELECT * FROM ADRESS

-- SELECT C.NAMESURNAME ADSOYAD ,C.EMAIL EMAIL , C.CITY SEHIR , A.POSTALCODE POSTAKODU ,A.ADDRESSTEXT ACIKADRES 
-- FROM CUSTOMERS C , ADDRESS A WHERE C.ID = A.CUSTOMERID

-- SELECT C.NAMESURNAME,C.EMAIL,A.CITY,A.POSTALCODE,A.ADRESSTEXT FROM CUSTOMERS C JOIN ADDRESSS A ON C.ID=A.CUSTOMERID WHERE C.NAMESURNAME='HASAN KAYA'
--JOIN Lİ YÖNTEM
SELECT C.NAMESURNAME,C.EMAIL,CT.CITY,A.POSTALCODE,A.ADRESSTEXT FROM CUSTOMERS C JOIN ADDRESSS A ON CUSTOMERS.ID=ADRESSS.CUSTOMERID JOIN CITIES CT ON CITIES.ID=ADDRESSS.CITYID JOIN TOWNS T ON T.ID=A.TOWNID JOIN DISTRICTS D ON D.ID =A.DISTRICTID
--GELENEKSEL YÖNTEM
SELECT C.NAMESURNAME,C.EMAIL,CT.CITY,A.POSTALCODE,A.ADRESSTEXT FROM CUSTOMERS C ,ADDRESSS A ,CITIES CT,TOWNS T,DISTRICTS D WHERE C.ID=ADRESSS.CUSTOMERID AND CT.ID=ADDRESS.CITYID AND A.TOWNID=T.ID AND D.ID=A.DISTRICTID

select * from CUSTOMERS
select * from adresss
delete from CUSTOMERS WHERE ID=2
--ÖNCE FOREİGN KEY İN OLDUĞU TABLODAKİ VERİLERİ SİL SONRA PRİMARY KEY OLAN TABLODAKİ VERİLERİ İLK ALTTAKİ 
delete FROM ADRESSS WHERE CUSTOMERID=2
SELECT U.ID,U.USER_NAME,A.CITY FROM USERS U  JOIN ADRESS A ON U.ID=A.USERID
SELECT U.ID,U.USER_NAME,A.CITY FROM USERS U INNER JOIN ADRESS A ON A.USERID = U.ID
SELECT U.ID,U.USER_NAME,A.CITY FROM USERS U LEFT JOIN ADRESS A ON A.USERID= U.ID
SELECT U.ID,U.USER_NAME,A.CITY FROM USERS U RIGHT JOIN ADRESS A ON A.USERID= U.ID
SELECT U.ID,U.USER_NAME,A.CITY FROM USERS U FULL JOIN ADRESS A ON A.USERID=U.ID

SELECT U.USER_NAME , SUM(S.TOTALPRICE), COUNT(S.ID) FROM SALES S LEFT JOIN USER U ON U.ID =S.USERID GROUP BY U.USER_NAME