SELECT C.CITY, D.DATE_,
    ISNULL(
    (SELECT SUM(O.TOTALPRICE)
    FROM ORDERS O
        JOIN ADDRESS A ON A.ID=O.ADDRESSID
    WHERE A.CITYID = C.ID AND CONVERT(DATE,O.DATE_) =D.DATE_ )
,0)
FROM CITIES C 
CROSS APPLY (SELECT *
    FROM DATES ) D
WHERE C.CITY='ARTVİN'

-- CROSS APPLY ORNEK 1 

SELECT C.CITY , ORDERINFO_MAX.MARKA, ORDERINFO_MAX.TUTAR , ORDERINFO_MIN.MARKA, ORDERINFO_MIN.TUTAR
FROM CITIES C CROSS APPLY 
(

SELECT TOP 1
        I.BRAND MARKA, SUM(OD.LINETOTAL) TUTAR
    FROM ORDERS O JOIN ORDERDETAILS OD ON O.ID = OD.ORDERID JOIN ADDRESS A ON A.ID = O.ADDRESSID JOIN ITEMS I ON I.ID=OD.ITEMID
    WHERE A.CITYID=C.ID
    GROUP BY I.BRAND
    ORDER BY SUM(OD.LINETOTAL) DESC
) ORDERINFO_MAX
CROSS APPLY
(

SELECT TOP 1
        I.BRAND MARKA, SUM(OD.LINETOTAL) TUTAR
    FROM ORDERS O JOIN ORDERDETAILS OD ON O.ID = OD.ORDERID JOIN ADDRESS A ON A.ID = O.ADDRESSID JOIN ITEMS I ON I.ID=OD.ITEMID
    WHERE A.CITYID=C.ID
    GROUP BY I.BRAND
    ORDER BY SUM(OD.LINETOTAL) ASC
) ORDERINFO_MIN

-- CROSS APPLY İÇİNDE KULLANDIĞIM SUBQUERY 
SELECT TOP 1
    I.BRAND MARKA, SUM(OD.LINETOTAL) TUTAR
FROM ORDERS O JOIN ORDERDETAILS OD ON O.ID = OD.ORDERID JOIN ADDRESS A ON A.ID = O.ADDRESSID JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE A.CITYID=1
GROUP BY I.BRAND
ORDER BY SUM(OD.LINETOTAL) DESC

-- CROSS APPLY ORNEK 2
-- HER BIR KULLANICININ EN SON ALISVERIS YAPTIGI TARIHI SEHRI VE ADRESI GETIREN SORGUYU CROSS APPLY ILE YAZINIZ 

SELECT U.NAMESURNAME , ORDER_DATE_INFO.TARIH, ORDER_DATE_INFO.SEHIR, ORDER_DATE_INFO.ILCE ,ORDER_DATE_INFO.MAHALLE,
ORDER_DATE_INFO.URUNADI,ORDER_DATE_INFO.TUTAR
FROM USERS U CROSS APPLY(
    SELECT TOP 1
        O.DATE_ TARIH, C.CITY SEHIR,T.TOWN ILCE,D.DISTRICT MAHALLE,I.ITEMNAME URUNADI,O.TOTALPRICE TUTAR
    FROM ORDERS O JOIN ADDRESS A ON A.ID=O.ADDRESSID 
    JOIN CITIES C ON C.ID=A.CITYID JOIN 
    TOWNS T ON T.ID=A.TOWNID JOIN DISTRICTS D ON D.ID=A.DISTRICTID
    JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID 
    JOIN ITEMS I ON I.ID=OD.ITEMID
    WHERE O.USERID=U.ID
    ORDER BY O.DATE_ DESC
) ORDER_DATE_INFO

-- ORNEK 2 DE KULLANDIĞIM CROSS APPLY QUERY KISMI  

SELECT TOP 1
        O.DATE_ TARIH, C.CITY SEHIR,T.TOWN ILCE,D.DISTRICT MAHALLE,I.ITEMNAME URUNADI,O.TOTALPRICE TUTAR
    FROM ORDERS O JOIN ADDRESS A ON A.ID=O.ADDRESSID 
    JOIN CITIES C ON C.ID=A.CITYID JOIN 
    TOWNS T ON T.ID=A.TOWNID JOIN DISTRICTS D ON D.ID=A.DISTRICTID
    JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID 
    JOIN ITEMS I ON I.ID=OD.ITEMID
    WHERE O.USERID=1
    ORDER BY O.DATE_ DESC