SELECT O.DATE_,I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL FROM ORDERS O  JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID JOIN ITEMS I ON I.ID=OD.ITEMID WHERE DATEPART(MONTH,DATE_) = 1 AND DATEPART(YEAR,DATE_) = 2020 ORDER BY DATE_ 
SELECT O.DATE_,I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL FROM ORDERS O  JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID JOIN ITEMS I ON I.ID=OD.ITEMID WHERE DATE_ BETWEEN '20200101' AND '2020-01-31 23:59:59' ORDER BY DATE_ DESC

-- ORNEK 2
SELECT U.NAMESURNAME,OD.ORDERID,O.DATE_,I.ITEMCODE,I.ITEMNAME,I.BRAND ,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL  FROM ORDERS O JOIN USERS U ON U.ID=O.USERID JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID JOIN ITEMS I ON I.ID=OD.ITEMID WHERE U.NAMESURNAME LIKE 'MEHMET ALİ KAZANOĞLU'

--ORNEK 3

SELECT C.CITY,T.TOWN FROM CITIES C JOIN TOWNS T ON T.CITYID=C.ID ORDER BY C.CITY,T.TOWN

-- ORNEK 4
SELECT * FROM ADDRESS
SELECT C.CITY ŞEHİR,T.TOWN İLÇE ,COUNT(DISTINCT A.USERID) MÜŞTERİSAYISI  FROM ADDRESS A JOIN USERS U ON U.ID=A.USERID JOIN CITIES C ON C.ID=A.CITYID JOIN TOWNS T ON T.ID=A.TOWNID WHERE CITY ='İSTANBUL' GROUP BY C.CITY,T.TOWN

-- ORNEK 5
SELECT * FROM ORDERDETAILS
SELECT U.NAMESURNAME ADSOYAD,DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) YAS,C.CITY SEHIR,O.DATE_ TARIH,O.ID SIPARISNO,O.TOTALPRICE TOPLAMTUTAR FROM ORDERS O JOIN USERS U ON U.ID=O.USERID JOIN ADDRESS A ON A.ID = O.ADDRESSID JOIN CITIES C ON C.ID=A.CITYID WHERE DATE_ BETWEEN '2020-03-01' AND '2020-03-31 23:59:59' AND DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 20 AND 30 ORDER BY YAS DESC

-- ORNEK 6 
SELECT A.USERID KULLANICIID,U.NAMESURNAME ADSOYAD,C.CITY SEHIR,COUNT(USERID) ADRESSAYISI FROM ADDRESS A JOIN USERS U ON U.ID=A.USERID JOIN CITIES C ON C.ID=A.CITYID GROUP BY A.USERID,U.NAMESURNAME,C.CITY ORDER BY U.NAMESURNAME  

-- ORNEK 7
SELECT * FROM ORDERS
SELECT TOP 10 C.CITY SEHIR ,I.ITEMCODE URUNKODU ,I.ITEMNAME URUNADI,I.BRAND MARKA,I.CATEGORY1 KATEGORI1,I.CATEGORY2 KATEGORI2,I.CATEGORY3 KATEGORI3, SUM(OD.AMOUNT) TOPLAMMIKTAR,SUM(OD.LINETOTAL) TOPLAMSATIS FROM ORDERS O JOIN ADDRESS A ON A.ID = O.ADDRESSID JOIN ORDERDETAILS OD ON  O.ID=OD.ORDERID JOIN CITIES C ON C.ID=A.CITYID JOIN ITEMS I ON I.ITEMCODE = OD.ITEMID WHERE C.CITY='İSTANBUL' AND O.DATE_ BETWEEN '2020-01-01' AND '2020-03-31 23:59:59' GROUP BY  C.CITY  ,I.ITEMCODE  ,I.ITEMNAME ,I.BRAND ,I.CATEGORY1 ,I.CATEGORY2 ,I.CATEGORY3 ORDER BY TOPLAMSATIS DESC

-- ORNEK 8 
SET LANGUAGE TURKISH
SELECT DATENAME(DW,DATE_) GUN,ROUND(SUM(TOTALPRICE),1) TOPLAMTUTAR,COUNT(ID) SIPARISSAYISI FROM ORDERS GROUP BY DATEPART(DW,DATE_), DATENAME(DW,DATE_) ORDER BY DATEPART(DW,DATE_)

-- Ornek 9 
SELECT DATEPART(HOUR,DATE_) SAAT, ROUND(SUM(TOTALPRICE),0) TOPLAMTUTAR,COUNT(ID) TOPLAMMIKTAR FROM ORDERS GROUP BY DATEPART(HOUR,DATE_) ORDER BY SAAT

-- ORNEK 10 
SELECT O.ID SIPARISNO,U.NAMESURNAME,C.CITY SEHIR,O.DATE_ SIPARISTARIHI,I.DATE_ SEVKTARIHI,DATEDIFF(HOUR,O.DATE_,I.DATE_) SEVKEDILMESURESI_SAAT FROM ORDERS O JOIN USERS U ON U.ID=O.USERID JOIN ADDRESS A ON A.ID=O.ADDRESSID JOIN CITIES C ON C.ID=A.CITYID JOIN INVOICES I ON O.ID=I.ORDERID
SELECT * FROM INVOICES

-- ORNEK 11
SELECT * FROM ADDRESS
SELECT AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) ORTALAMASEVKSURESİ FROM ORDERS O JOIN INVOICES I ON I.ORDERID=O.ID
SELECT C.CITY ,AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) FROM ORDERS O JOIN INVOICES I ON I.ORDERID=O.ID JOIN ADDRESS A ON A.ID=O.ADDRESSID JOIN CITIES C ON C.ID=A.CITYID GROUP BY C.CITY
-- SELECT C.REGION ,AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) FROM ORDERS O JOIN INVOICES I ON I.ORDERID=O.ID JOIN ADDRESS A ON A.ID=O.ADDRESSID JOIN CITIES C ON C.ID=A.CITYID GROUP BY C.REGION

-- ORNEK 12
SELECT O.ID SIPARISNO,O.DATE_ SIPARISTARIHI , I.DATE_ FATURATARIHI , O.TOTALPRICE TOPLAMTUTAR , DATENAME(MONTH,O.DATE_) SIPARISTARIHI,DATENAME(MONTH,I.DATE_) FATURATARIHI  FROM ORDERS O JOIN INVOICES I ON I.ORDERID = O.ID WHERE  DATEPART(MONTH,O.DATE_) <> DATEPART(MONTH,I.DATE_) 

-- ORNEK 13 
SELECT DATENAME(MONTH,O.DATE_) , COUNT(DATENAME(MONTH,I.DATE_))  FROM ORDERS O JOIN INVOICES I ON I.ORDERID = O.ID WHERE DATENAME(MONTH,O.DATE_) <> DATENAME(MONTH,I.DATE_) GROUP BY DATENAME(MONTH,O.DATE_),DATEPART(MONTH,O.DATE_) ORDER BY DATEPART(MONTH,O.DATE_)

--ORNEK 14 
SELECT C.CITY SEHIR ,U.GENDER CINSIYET ,COUNT(A.ID) KULLANICISAYISI  FROM ADDRESS A JOIN USERS U ON U.ID=A.USERID JOIN CITIES C ON C.ID=A.CITYID GROUP BY C.CITY,U.GENDER ORDER BY 1,2

-- ORNEK 15 
SELECT I.CATEGORY1 ANAKATEGORI,I.CATEGORY2 ALTKATEGORI,SUM(OD.LINETOTAL)   FROM ORDERDETAILS OD JOIN  ITEMS I ON I.ID=OD.ITEMID  JOIN  ORDERS O ON O.ID=OD.ORDERID   GROUP BY I.CATEGORY1,I.CATEGORY2 ORDER BY I.CATEGORY1,SUM(OD.LINETOTAL) DESC

-- ORNEK 16
SELECT C.REGION, C.CITY SEHIRLER , I.CATEGORY1 KATEGORILER, SUM(OD.LINETOTAL)  FROM ORDERS O JOIN ORDERDETAILS OD ON O.ID = OD.ORDERID JOIN ITEMS I ON I.ID=OD.ITEMID JOIN ADDRESS A ON A.ID = O.ADDRESSID JOIN CITIES C ON C.ID = A.CITYID WHERE I.CATEGORY1 IN ('GIDA','DETERJAN') GROUP BY C.REGION, C.CITY , I.CATEGORY1 ORDER BY  1,2

-- ORNEK 17  17.49
    SELECT * FROM ITEMS
SELECT * FROM ORDERDETAILS
SELECT I.ITEMCODE URUNKODU , I.ITEMNAME URUNDADI ,I.UNITPRICE LISTEFIYATI ,SUM(OD.AMOUNT) TOPLAMADET , ROUND(SUM(OD.LINETOTAL),0) TOPLAMTUTAR,MIN(OD.UNITPRICE) MINFIYAT,MAX(OD.UNITPRICE) MAXFIYAT,ROUND(AVG(OD.UNITPRICE),2) ORTFIYAT,SUM(I.UNITPRICE*OD.AMOUNT) LISTEFIYATISATIS , ROUND((SUM(OD.LINETOTAL) - SUM(I.UNITPRICE*OD.AMOUNT) ),0) KAR_ZARAR ,ROUND((100 * ROUND((SUM(OD.LINETOTAL) - SUM(I.UNITPRICE*OD.AMOUNT) ),0) / SUM(I.UNITPRICE*OD.AMOUNT)  ),2 )  FROM ORDERDETAILS OD JOIN ITEMS I ON I.ID=OD.ITEMID GROUP BY I.ITEMCODE  , I.ITEMNAME  ,I.UNITPRICE  ORDER BY TOPLAMADET DESC

-- ORNEK 18 
SELECT I.ITEMCODE URUNKODU , I.ITEMNAME URUNDADI ,I.UNITPRICE LISTEFIYATI ,
SUM(OD.AMOUNT) TOPLAMADET , ROUND(SUM(OD.LINETOTAL),0) TOPLAMTUTAR,
MIN(OD.UNITPRICE) MINFIYAT,MAX(OD.UNITPRICE) MAXFIYAT,ROUND(AVG(OD.UNITPRICE),2) ORTFIYAT,
SUM(I.UNITPRICE*OD.AMOUNT) LISTEFIYATISATIS , ROUND((SUM(OD.LINETOTAL) - SUM(I.UNITPRICE*OD.AMOUNT) ),0) KAR_ZARAR ,ROUND((100 * ROUND((SUM(OD.LINETOTAL) - SUM(I.UNITPRICE*OD.AMOUNT) ),0) / SUM(I.UNITPRICE*OD.AMOUNT)  ),2 )  FROM ORDERDETAILS OD JOIN ITEMS I ON I.ID=OD.ITEMID GROUP BY I.ITEMCODE  , I.ITEMNAME  ,I.UNITPRICE  ORDER BY TOPLAMADET DESC

--BU ALTTAKİ YÖNTEMİ YENİ ÖĞRENDİM HOCA BUNU DA GÖRMÜŞ OLUN DEDİ 
SELECT TOP 10 *,TOPLAMTUTAR-LISTEFIYATISATIS KAR_ZARAR,ROUND(100*(TOPLAMTUTAR-LISTEFIYATISATIS)/LISTEFIYATISATIS,2) KAR_ZARAR_YUZDE FROM (
SELECT I.ITEMCODE URUNKODU , I.ITEMNAME URUNDADI ,I.UNITPRICE LISTEFIYATI ,SUM(OD.AMOUNT) TOPLAMADET , ROUND(SUM(OD.LINETOTAL),0) TOPLAMTUTAR,MIN(OD.UNITPRICE) MINFIYAT,MAX(OD.UNITPRICE) MAXFIYAT,
ROUND(AVG(OD.UNITPRICE),2) ORTFIYAT,SUM(I.UNITPRICE*OD.AMOUNT) LISTEFIYATISATIS 
  FROM ORDERDETAILS OD JOIN ITEMS I ON I.ID=OD.ITEMID GROUP BY I.ITEMCODE  , I.ITEMNAME  ,I.UNITPRICE 
)  T 
ORDER BY KAR_ZARAR_YUZDE DESC