SELECT * INTO USERS_YEDEK FROM USERS

SELECT * FROM USERS_YEDEK
DELETE FROM USERS
SELECT * FROM USERS WHERE BIRTHDATE BETWEEN '1950-01-01' AND '1960-12-31'
DROP TABLE USERS
-- ALT SATIRDAKI KOPYAYI GERI ALMA NORMALDE ÇALIŞMADI ÇÜNKÜ ZATEN BİR USERS TABLOSU VAR DEDİ BU YÜZDEN UST SATIRDA USERS TABLOSUNU SİLDİK VE OYLE KOPYALAADIK
SELECT * INTO USERS FROM USERS_YEDEK

-- INSERT INTO SELECT ORNEK 1
DELETE FROM USERS_YEDEK WHERE ID = 20
TRUNCATE TABLE USERS
SELECT * FROM USERS
SET IDENTITY_INSERT USERS ON 
INSERT INTO  USERS ([ID],[USERNAME_],[PASSWORD_],[NAMESURNAME],[EMAIL],[GENDER],[BIRTHDATE],[CREATEDDATE],[TELNR1],[TELNR2]) 
SELECT [ID],[USERNAME_],[PASSWORD_],[NAMESURNAME],[EMAIL],[GENDER],[BIRTHDATE],[CREATEDDATE],[TELNR1],[TELNR2] FROM USERS_YEDEK 

--INSERT INTO ORNEK 2 
SELECT * FROM USERS WHERE BIRTHDATE BETWEEN '1950-01-01' AND '1960-12-31'
DELETE FROM USERS WHERE BIRTHDATE BETWEEN '1950-01-01' AND '1960-12-31'

SET IDENTITY_INSERT USERS ON

SELECT * FROM USERS_YEDEK WHERE ID NOT IN (SELECT ID FROM USERS)
INSERT INTO USERS ([ID],[USERNAME_],[PASSWORD_],[NAMESURNAME],[EMAIL],[GENDER],[BIRTHDATE],[CREATEDDATE],[TELNR1],[TELNR2])
SELECT [ID],[USERNAME_],[PASSWORD_],[NAMESURNAME],[EMAIL],[GENDER],[BIRTHDATE],[CREATEDDATE],[TELNR1],[TELNR2] FROM USERS_YEDEK
WHERE ID NOT IN (SELECT ID FROM USERS)

-- SELECT * INTO ILE TABLONUN BOŞ (VERISIZ) BIR KOPYASINI ALMA 
SELECT * INTO USERS2 FROM USERS WHERE 1=0


-- DATAWAREHOUSE OLUŞTURMA
SELECT 
O.ID ORDERID , O.DATE_ , O.TOTALPRICE ,O.STATUS_,
U.ID USERID,U.BIRTHDATE,U.CREATEDDATE,U.USERNAME_,U.NAMESURNAME ,U.EMAIL,U.GENDER,U.TELNR1,U.TELNR2,
C.CITY,T.TOWN,D.DISTRICT ,A.ID ADDRESSID ,A.POSTALCODE , A.ADDRESSTEXT,
I.ID,I.ITEMCODE,I.ITEMNAME,I.BRAND,I.UNITPRICE ITEMUNITPRICE,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,
OD.ID ORDERDETAILID,OD.AMOUNT,OD.UNITPRICE ORDERUNITPRICE,OD.LINETOTAL,
INV.ID INVOICEID,INV.DATE_ INVOICEDATE,INV.CARGOFICHENO
INTO SALES
 FROM ORDERS O JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID JOIN USERS U ON U.ID=O.USERID 
JOIN ADDRESS A ON A.ID=O.ADDRESSID JOIN CITIES C ON C.ID=A.CITYID JOIN TOWNS T ON T.ID = A.TOWNID JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID JOIN INVOICES INV on INV.ORDERID=O.ID JOIN INVOICEDETAILS ID ON ID.INVOICEID=INV.ID

SELECT COUNT(ID) FROM SALES