select * from CITIES

SELECT U.NAMESURNAME,COUNT(A.USERID) ADRESSAYISI FROM USERS U ,ADDRESS A WHERE A.USERID=U.ID  GROUP BY U.NAMESURNAME ORDER BY ADRESSAYISI DESC
SELECT U.NAMESURNAME,COUNT(A.USERID) FROM USERS U JOIN ADDRESS A ON U.ID=A.USERID GROUP BY U.NAMESURNAME
SELECT U.NAMESURNAME,(SELECT COUNT(USERID) FROM ADDRESS WHERE USERID=U.ID) AS ADRESSAYISI FROM USERS U ORDER BY ADRESSAYISI DESC

SELECT * FROM ORDERS

--ŞEHRİ İSTANBUL OLAN SATIŞLARI GETİRME 
SELECT O.ID,O.DATE_,O.TOTALPRICE FROM ORDERS O JOIN ADDRESS A ON O.ADDRESSID=A.ID JOIN CITIES C ON C.ID=A.CITYID
WHERE C.CITY='İSTANBUL'

--ŞEHRİ İSTANBUL OLAN SATIŞLARI GETİRME 
SELECT O.ID,O.DATE_ , O.TOTALPRICE FROM ORDERS O WHERE ADDRESSID IN (
    SELECT ID FROM ADDRESS WHERE CITYID IN (
        SELECT ID FROM CITIES WHERE CITY='İSTANBUL'
    )
) ORDER BY TOTALPRICE DESC

-- SET STATISTICS IO ON 
-- ÜRÜN ANALİZİ JOIN
SELECT I.ID  , I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.BRAND MARKA ,SUM(OD.AMOUNT) TOPLAM_ADET, SUM(OD.LINETOTAL) TOPLAM_CIRO ,
MIN(OD.UNITPRICE) ENDUSUK_FIYAT,
MAX(OD.UNITPRICE) ENYUKSEK_FIYAT,
ROUND(AVG(OD.UNITPRICE),2) ORTALAMA_FIYAT
 FROM ITEMS I JOIN ORDERDETAILS OD ON OD.ITEMID=I.ID
 GROUP BY I.ID,I.ITEMCODE ,I.ITEMNAME,I.BRAND

-- SET STATISTICS IO ON 

-- ÜRÜN ANALİZİ SUBQUERY 
SELECT I.ID  , I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.BRAND MARKA ,
(SELECT COUNT(AMOUNT)   FROM ORDERDETAILS OD WHERE OD.ITEMID=I.ID ) TOPLAM_ADET,
(SELECT COUNT(LINETOTAL)   FROM ORDERDETAILS OD WHERE OD.ITEMID=I.ID ) TOPLAM_CIRO,
(SELECT MIN(UNITPRICE)   FROM ORDERDETAILS OD WHERE OD.ITEMID=I.ID ) EN_DUSUK_FIYAT,
(SELECT MAX(UNITPRICE)   FROM ORDERDETAILS OD WHERE OD.ITEMID=I.ID ) EN_YUKSEK_FIYAT,
(SELECT ROUND(AVG(OD.UNITPRICE),2)   FROM ORDERDETAILS OD WHERE OD.ITEMID=I.ID ) ORTALAMA_FIYAT_FIYAT
FROM ITEMS I

SELECT I.BRAND MARKA,
(SELECT COUNT(DISTINCT CATEGORY1) FROM ITEMS WHERE BRAND = I.BRAND) ANA_KATEGORI_SAYISI,
(SELECT COUNT(DISTINCT CATEGORY2) FROM ITEMS WHERE BRAND = I.BRAND) ALT_KATEGORI_SAYISI,
(SELECT COUNT(*) FROM ITEMS WHERE BRAND = I.BRAND) URUN_SAYISI
FROM ITEMS I

-- SUBQUERY ORNEK 3

SELECT C.CITY ,
(
    SELECT   SUM(OD.LINETOTAL) FROM ORDERS O JOIN ORDERDETAILS OD ON O.ID = OD.ORDERID JOIN ADDRESS A ON O.ADDRESSID= A.ID JOIN ITEMS I ON I.ID=OD.ITEMID  WHERE  I.CATEGORY1='GIDA' AND A.CITYID=C.ID
) GIDA,
(
    SELECT   SUM(OD.LINETOTAL) FROM ORDERS O JOIN ORDERDETAILS OD ON O.ID = OD.ORDERID JOIN ADDRESS A ON O.ADDRESSID= A.ID JOIN ITEMS I ON I.ID=OD.ITEMID  WHERE  I.CATEGORY1='DETERJAN' AND A.CITYID=C.ID
) DETERJAN
  FROM CITIES C 

-- SUBQUERY ORNEK 4

SELECT C.CITY ,
(
    SELECT COUNT(DISTINCT USERID) FROM USERS U JOIN ADDRESS A ON A.USERID = U.ID WHERE U.GENDER='E' AND A.CITYID = C.ID
) ERKEK,
(
    SELECT COUNT(DISTINCT USERID) FROM USERS U JOIN ADDRESS A ON A.USERID = U.ID WHERE U.GENDER='K' AND A.CITYID = C.ID
) KADIN
  FROM CITIES C

--  BU ALTTAKINI SUBQUERY ICINDE KULLANDIK
SELECT COUNT(DISTINCT USERID) FROM USERS U JOIN ADDRESS A ON A.USERID = U.ID WHERE U.GENDER='E' AND A.CITYID = 1

-- SUBQUERY ORNEK 5
-- ŞEHİRLERİN AYLARA GÖRE SATIŞINI AYLAR YUKARIDA YANYANA SÜTUNLAR  OLUCAK ŞEKİLDE GETİRİNİZ  / EN SONA TÜM AYLARIN TOPLAMNI DA EKLEDİK
SELECT C.CITY,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =1 ) OCAK,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =2 ) ŞUBAT,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =3 ) MART,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =4 ) NISAN,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =5 ) MAYIS,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =6 ) HAZIRAN,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =7 ) TEMMUZ,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =8 ) AGUSTOS,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =9 ) EYLUL,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =10  )EKIM,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =11  )KASIM,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =12 ) ARALIK,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID ) TOPLAM

 FROM CITIES C
-- BU ALTTAKİ SUBQUERY İÇİNDE KULLANDIĞIMIZ SORGU 
SELECT SUM(O.TOTALPRICE) OCAK FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=1 AND DATEPART(MONTH , O.DATE_) =1 

-- SUBQUERY ORNEK 6

SELECT BOLGE , SUM(OCAK) OCAK ,SUM(SUBAT) SUBAT ,SUM(MART) MART ,SUM(NISAN) NISAN ,SUM(MAYIS) MAYIS,SUM(HAZIRAN) HAZIRAN ,
SUM(TEMMUZ) TEMMUZ , SUM(AGUSTOS) AGUSTOS ,SUM(EYLUL) EYLUL , SUM(EKIM) EKIM ,SUM(KASIM) KASIM, SUM(ARALIK) ARALIK,SUM(TOPLAM) TOPLAM 

FROM (
 SELECT C.REGION BOLGE , C.CITY,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =1 ) OCAK,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =2 ) ŞUBAT,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =3 ) MART,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =4 ) NISAN,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =5 ) MAYIS,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =6 ) HAZIRAN,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =7 ) TEMMUZ,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =8 ) AGUSTOS,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =9 ) EYLUL,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =10  )EKIM,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =11  )KASIM,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID AND DATEPART(MONTH , O.DATE_) =12 ) ARALIK,
(SELECT SUM(O.TOTALPRICE)  FROM ORDERS O JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID ) TOPLAM

 FROM CITIES C
) T GROUP by BOLGE 
ORDER BY BOLGE

-- SUBQUERY ÖRNEK 7
-- HER BIR SEHIR ICIN EN COK ALISVERIS YAPILAN KATEGORI ILE EN AZ ALISVERIS YAPILAN KATEGORILERI (CATEGORY2) YAZDIRAN SORGUYU YAZINIZ
SELECT C.CITY,
(
    SELECT TOP 1 I.CATEGORY2  FROM ORDERS O JOIN ADDRESS A ON O.ADDRESSID=A.ID JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID JOIN ITEMS I ON I.ID=OD.ITEMID WHERE A.CITYID=C.ID GROUP BY I.CATEGORY2  ORDER BY SUM(OD.LINETOTAL)  DESC
) EN_FAZLA_SATILAN_KATEGORI,(
    SELECT TOP 1 SUM(OD.LINETOTAL)  FROM ORDERS O JOIN ADDRESS A ON O.ADDRESSID=A.ID JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID JOIN ITEMS I ON I.ID=OD.ITEMID WHERE A.CITYID=C.ID GROUP BY I.CATEGORY2  ORDER BY SUM(OD.LINETOTAL)  DESC
) TUTAR ,
(
    SELECT TOP 1 I.CATEGORY2  FROM ORDERS O JOIN ADDRESS A ON O.ADDRESSID=A.ID JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID JOIN ITEMS I ON I.ID=OD.ITEMID WHERE A.CITYID=C.ID GROUP BY I.CATEGORY2  ORDER BY SUM(OD.LINETOTAL)  
) EN_AZ_SATILAN_KATEGORI,(
    SELECT TOP 1 SUM(OD.LINETOTAL)  FROM ORDERS O JOIN ADDRESS A ON O.ADDRESSID=A.ID JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID JOIN ITEMS I ON I.ID=OD.ITEMID WHERE A.CITYID=C.ID GROUP BY I.CATEGORY2  ORDER BY SUM(OD.LINETOTAL)  
) TUTAR 

  FROM CITIES C

--SORGU İÇİNDE KULLANDIĞIM SUBWUERY 
SELECT TOP 1 I.CATEGORY2 EN_FAZLA_SATILAN_KATEGORI,SUM(LINETOTAL) TUTAR FROM ORDERS O JOIN ADDRESS A ON O.ADDRESSID=A.ID JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID JOIN ITEMS I ON I.ID=OD.ITEMID WHERE A.CITYID=1 GROUP BY I.CATEGORY2  ORDER BY TUTAR DESC

-- SUBQUERY ORNEK 8 
-- HER BIR SEHIR RICIN EN COK ALISVERIS YAPILAN MARKA ILE EN AZ ALISVERIS YAPILAN MARKALARI GETIREN SORGUYU YAZINIZ

SELECT C.CITY ,
(
    SELECT TOP 1 I.BRAND BRAND  FROM ORDERS O JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID JOIN ITEMS I ON I.ID=OD.ITEMID JOIN ADDRESS A ON A.ID= O.ADDRESSID  WHERE A.CITYID=C.ID GROUP BY I.BRAND ORDER BY SUM(OD.LINETOTAL) DESC
) EN_FAZLA_SATILAN_MARKA ,
(
    SELECT TOP 1  SUM(OD.LINETOTAL) TUTAR FROM ORDERS O JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID JOIN ITEMS I ON I.ID=OD.ITEMID JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID  GROUP BY I.BRAND  ORDER BY SUM(OD.LINETOTAL) DESC

) TUTAR,
(
    SELECT TOP 1 I.BRAND BRAND FROM ORDERS O JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID JOIN ITEMS I ON I.ID=OD.ITEMID JOIN ADDRESS A ON A.ID= O.ADDRESSID  WHERE A.CITYID=C.ID  GROUP BY I.BRAND   ORDER BY SUM(OD.LINETOTAL) 
) EN_AZ_SATILAN_MARKA ,
(
    SELECT TOP 1 SUM(OD.LINETOTAL) TUTAR FROM ORDERS O JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID JOIN ITEMS I ON I.ID=OD.ITEMID JOIN ADDRESS A ON A.ID= O.ADDRESSID WHERE A.CITYID=C.ID  GROUP BY I.BRAND  ORDER BY SUM(OD.LINETOTAL) 

) TUTAR
 FROM CITIES C 

SELECT I.BRAND BRAND , SUM(OD.LINETOTAL) TUTAR FROM ORDERS O JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID JOIN ITEMS I ON I.ID=OD.ITEMID JOIN ADDRESS A ON A.ID= O.ADDRESSID    ORDER BY SUM(OD.LINETOTAL) DESC
SELECT  SUM(OD.LINETOTAL) TUTAR FROM ORDERS O JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID JOIN ITEMS I ON I.ID=OD.ITEMID JOIN ADDRESS A ON A.ID= O.ADDRESSID    ORDER BY SUM(OD.LINETOTAL) DESC

-- SUBQUERY ORNEK 9
-- HER MARKA ICIN EN ÇOK SATILAN KATEGORI VE EN AZ SATILAN KATEGORILERI GETIREN SORGUYU YAZINIZ 

SELECT DISTINCT I1.BRAND, 
(
SELECT TOP 1 I.CATEGORY1 FROM ORDERDETAILS OD JOIN ITEMS I ON I.ID=OD.ITEMID WHERE I.BRAND=I1.BRAND GROUP BY I.CATEGORY1 ORDER BY SUM(OD.LINETOTAL) DESC
) AS  EN_FAZLA_SATILAN_KATEGORI,
(
    SELECT TOP 1 SUM(OD.LINETOTAL) FROM ORDERDETAILS OD JOIN ITEMS I ON I.ID=OD.ITEMID WHERE I.BRAND=I1.BRAND GROUP BY I.CATEGORY1 ORDER BY SUM(OD.LINETOTAL) DESC
) AS  TUTAR ,
(
SELECT TOP 1 I.CATEGORY1 FROM ORDERDETAILS OD JOIN ITEMS I ON I.ID=OD.ITEMID WHERE I.BRAND=I1.BRAND GROUP BY I.CATEGORY1 ORDER BY SUM(OD.LINETOTAL) ASC
) AS  EN_AZ_SATILAN_KATEGORI,
(
    SELECT TOP 1 SUM(OD.LINETOTAL) FROM ORDERDETAILS OD JOIN ITEMS I ON I.ID=OD.ITEMID WHERE I.BRAND=I1.BRAND GROUP BY I.CATEGORY1 ORDER BY SUM(OD.LINETOTAL) ASC
) AS  TUTAR 


 FROM ITEMS I1 

 -- SORGUDA KULLANDIĞIM SUBQUERY ALTTAKİLER
SELECT * FROM ORDERDETAILS
SELECT SUM(LINETOTAL) FROM ORDERDETAILS OD JOIN ITEMS I ON I.ID=OD.ITEMID GROUP BY I.CATEGORY1 ORDER BY SUM(LINETOTAL) DESC

-- SUBWUERY ORNEK 10 
-- HER BIR KATEGORI ICIN EN COK SATILAN VE EN AZ SATILAN MARKAYI YANYANA YAZDIRINIZ

SELECT DISTINCT I1.CATEGORY1,
(
SELECT TOP 1 I.BRAND FROM ORDERDETAILS OD JOIN ITEMS I ON I.ID=OD.ITEMID WHERE I.CATEGORY1=I1.CATEGORY1 GROUP BY I.BRAND ORDER BY SUM(OD.LINETOTAL) DESC
) AS  EN_FAZLA_SATILAN_MARKA,
(
SELECT TOP 1 SUM(OD.LINETOTAL)  FROM ORDERDETAILS OD JOIN ITEMS I ON I.ID=OD.ITEMID WHERE I.CATEGORY1=I1.CATEGORY1 GROUP BY I.BRAND ORDER BY SUM(OD.LINETOTAL) DESC
) AS  TUTAR ,

(
SELECT TOP 1 I.BRAND FROM ORDERDETAILS OD JOIN ITEMS I ON I.ID=OD.ITEMID WHERE I.CATEGORY1=I1.CATEGORY1 GROUP BY I.BRAND ORDER BY SUM(OD.LINETOTAL) 
) AS  EN_AZ_SATILAN_MARKA,
(
SELECT TOP 1 SUM(OD.LINETOTAL) TUTAR FROM ORDERDETAILS OD JOIN ITEMS I ON I.ID=OD.ITEMID WHERE I.CATEGORY1=I1.CATEGORY1 GROUP BY I.BRAND ORDER BY SUM(OD.LINETOTAL) 
) AS  TUTAR
  FROM ITEMS I1

SELECT I.BRAND MARKALAR,SUM(OD.LINETOTAL) TUTAR FROM ITEMS I JOIN ORDERDETAILS OD ON OD.ITEMID=I.ID GROUP BY I.BRAND ORDER BY SUM(OD.LINETOTAL) DESC

-- SUBQUERY ORNEK 11
-- 2 DEN FAZLA ADRESİ OLAN KULLANICILARI SUBQUERY İLE GETİRİNİZ

-- KLASIK JOIN KULLANIMI
SELECT U.NAMESURNAME,COUNT(A.ID) FROM USERS U JOIN ADDRESS A ON A.USERID=U.ID  GROUP BY U.NAMESURNAME,U.ID HAVING  COUNT(A.ID)>2

-- SUBQUERY ILE SORGU OLUSTURMA
SELECT U.NAMESURNAME ,
(SELECT COUNT (A.ID) ADRES FROM ADDRESS A WHERE A.USERID=U.ID  
) ADRESSAYISI
   FROM USERS U WHERE (SELECT COUNT (A.ID) ADRES FROM ADDRESS A WHERE A.USERID=U.ID )>2 ORDER BY ADRESSAYISI DESC

-- DYNAMIC VİEW YONTEMI 
SELECT * FROM (
SELECT U.NAMESURNAME ,
(SELECT COUNT (A.ID) ADRES FROM ADDRESS A WHERE A.USERID=U.ID  
) ADRESSAYISI
   FROM USERS U WHERE (SELECT COUNT (A.ID) ADRES FROM ADDRESS A WHERE A.USERID=U.ID )>2 
) T 
WHERE ADRESSAYISI >2

-- SUBQUERY ORNEK 12
--AYNI ŞEHİRDE 2 DEN FAZLA ADRESİ OLAN KULLANICILARI GETİRİNİZ

SELECT * FROM (
SELECT U.ID,U.NAMESURNAME ,
(SELECT COUNT(ID) FROM ADDRESS  WHERE USERID=U.ID) TOPLAM_ADRES_SAYISI,
(SELECT   COUNT(ID) FROM ADDRESS  WHERE USERID=U.ID GROUP BY CITYID HAVING COUNT(ID) > 2)  AYNI_SEHIRDEKI_ADRES_SAYISI
 FROM USERS U )T WHERE AYNI_SEHIRDEKI_ADRES_SAYISI >2


-- SUBQUERY ORNEK 13 
-- HER BIR KULLANICININ EN SON ALIŞVERİŞ YAPTIĞI TARİHİ , ŞEHRİ VE ADRESİ GETİREN SORGUYU SUBQUERY İLE YAZINIZ 

SELECT U1.ID,U1.NAMESURNAME,
(SELECT TOP 1 O.DATE_ FROM ORDERS O  JOIN USERS U ON U.ID= O.USERID WHERE O.USERID=U1.ID ORDER BY O.DATE_ DESC ) SON_ALISVERIS_YAPILAN_TARIH,
(SELECT TOP 1 C.CITY FROM ORDERS O JOIN USERS U ON U.ID= O.USERID JOIN ADDRESS A ON A.ID=O.ADDRESSID JOIN CITIES C ON C.ID=A.CITYID WHERE O.USERID=U1.ID ORDER BY O.DATE_ DESC ) SON_ALISVERIS_YAPILAN_SEHIR,
(SELECT TOP 1 A.ADDRESSTEXT FROM ORDERS O JOIN USERS U ON U.ID= O.USERID JOIN ADDRESS A ON A.ID=O.ADDRESSID JOIN CITIES C ON C.ID=A.CITYID WHERE O.USERID=U1.ID ORDER BY O.DATE_ DESC ) SON_ALISVERIS_YAPILAN_ADRES,
(SELECT TOP 1 I.ITEMNAME FROM ORDERS O JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID JOIN ITEMS I ON I.ID=OD.ITEMID WHERE O.USERID=U1.ID ORDER BY O.DATE_ DESC ,OD.ID DESC ) SON_ALINAN_URUN
 FROM USERS U1

SELECT TOP 1 O.DATE_ FROM ORDERS O JOIN USERS U ON U.ID= O.USERID WHERE O.USERID=U.ID ORDER BY O.DATE_ DESC 
SELECT TOP 1 C.CITY FROM ORDERS O JOIN USERS U ON U.ID= O.USERID JOIN ADDRESS A ON A.ID=ORDERS.ADDRESSID JOIN CITIES C ON C.ID=A.CITYID WHERE O.USERID=U1.ID ORDER BY O.DATE_ DESC 
SELECT TOP 1 I.ITEMNAME FROM ORDERS O JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID JOIN ITEMS I ON I.ID=OD.ITEMID WHERE O.USERID=U1.ID  ORDER BY O.DATE_ DESC ,OD.ID DESC